### ISSUE TITLE
Dashboard: Tampilkan daftar semua pelanggan SaaS

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#1]
Tampilkan daftar semua site OpenSID SaaS di server ybs.

Tampilkan:

- identitas desa
- status langganan
- tanggal mulai/akhir
- premium/umum, symlink ke mana
- backup terakhir

Cari berdasarkan identitas desa.

Filter:

- status langganan
- premium/umum, symlink

Urut:

- identitas desa
- status langganan
- tanggal mulai/akhir
- premium/umum, symlink

**Comment by apidong** [comment]
sudah di perbaiki melalui pr https://github.com/OpenSID/dashboard-saas/pull/16
