### ISSUE TITLE
Dashboard: setup awal OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#10]
- [x] buat database
- [x] buat folder desa, termasuk isi desa/config/database.php
- [x] buat symlink sesuai dengan status langganan
- [x] tambahkan kode desa dan token ke desa/config/config.php

Setelah setup awal ini, OpenSID dapat dibuka, dan akan secara otomatis mengisi data awal dan pemasangan identitas desa beserta status langganan,

**Comment by scqolbu24** [comment]
sudah diterapkan pada saat menjalankan API = {{host}}/api/newsite
