### ISSUE TITLE
Kode Aktifasi Tema Pro

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#100]
Berdasarkan pertemuan dengan pelaksana pada Hari Kamis, 29 September 2022, terdapat review dari Pak Ariandi bahwa Bagaimana cara memasukan aktifasi tema pro. dari kasus tersebut harapannya tema pro dapat dimasukan melalui layanan, sehingga dibuatkan API untuk memasukan aktifasi dari masing-masing tema pro.

Untuk melakukan aktifasi dari masing-masing tema berbeda, Adapun langkah-langkahnya sebagai berikut:

- [ ] Tema Denatra https://github.com/ariandii/denatra
- [ ] Tema Denava https://github.com/ariandii/denava
- [ ] Tema Silir (Pelaksana mengirimkan domain yang berlangganan tema pro ke pembuat tema silir)
- [ ] Tema Batuah (Pelaksana mengirimkan domain yang berlangganan tema pro ke pembuat tema batuah)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/88
