### ISSUE TITLE
Penyesuaian konfigurasi pada file config.php

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#102]
Berdasarkan issue https://github.com/OpenSID/wiki-saas/issues/100, maka perlu ada penyesuaian konfigurasi pada file desa/config/config.php di perintah-perintah tertentu, diantaranya:

- [x] Penyesuaian ketika Perpanjangan OpenSID Premium
- [x] Penyesuaian ketika Perpanjangan OpenSID Siap Pakai
- [x] Penyesuaian ketika terdapat perubahan domain

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/94
