### ISSUE TITLE
Permission install opensid siap pakai dan generate site premium

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#104]
Pada saat mempersiapkan OpenSID Siap Pakai ketika menjalankan perintah pada langkah 5 pada https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#instal-opensid-siap-pakai yaitu `php artisan opensid:install-saas --domain=namadomain` terjadi error seperti berikut:
![error install opensid siap pakai](https://user-images.githubusercontent.com/68048807/194967128-1f3b8eb7-d9db-4c70-94f1-070ed6f6a620.JPG)

Error tersebut dapat diatasi dengan menambahkan sudo sehingga menjadi `sudo php artisan opensid:install-saas --domain=namadomain` 

untuk kasus tersebut dapat diatasi, namun untuk generate Build Site Premium, API, dan PBB perlu ditambahkan dalam script agar ketika generate berjalan dengan normal.

Infromasi tambahan:
Ketika menambahkan `sudo` akan mempengaruhi ke perintah-perintah lainnya di langkah ke 6 dan seterusnya, serta menimbulkan issue pada [#105 Permission directory html ](https://github.com/OpenSID/wiki-saas/issues/105)

**Comment by roaddee** [comment]
Seharusnya pakai root saja untuk install was nya jadi setiap perintah Tanpa diawali sudo

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/92
