### ISSUE TITLE
Permission directory html

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#105]
Permission Production
![permission production](https://user-images.githubusercontent.com/68048807/194969211-4fae021c-bca3-4ada-9092-6ec2c3a03d89.JPG)

Permission Development
![permission development](https://user-images.githubusercontent.com/68048807/194969247-9e638a7b-bc6a-4f6b-9208-9351165abb33.JPG)

Saat ini ada perbedaan permission pada gambar diatas antara production dan development, dimungkinkan akan mempengaruhi perintah-perintah yang ada saat ini, perlu disesuaikan permission tersebut agar dapat berjalan normal.

Penyesuaian tersebut sebaiknya dimasukan ke script.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/92
