### ISSUE TITLE
Masukan Panduan untuk keterangan error dan solusinya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#106]
![Image](https://user-images.githubusercontent.com/68048807/195061478-31d89914-4959-4e84-9ddd-45482cd64f30.JPG)

![Permission dennied](https://user-images.githubusercontent.com/68048807/195204741-a067bd0e-24dd-44ae-bcac-df237c8e3a72.JPG)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui panduan
https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#instal-layanan-opensid-siap-pakai

**Comment by devrakapriyo** [comment]
<img width="1440" alt="Screen Shot 2022-10-12 at 14 45 48" src="https://user-images.githubusercontent.com/36557759/195293722-d21870ca-c178-427e-98e8-86dfe4243881.png">

mas @scqolbu24  untuk ketentuan GB nya itu tidak ada ketentuan?

**Comment by scqolbu24** [comment]
@devrakapriyo  itu nantinya menyesuaikan, saat ini belum diketahui berapa GB minimal untuk berapa desa per VPS
