### ISSUE TITLE
BUG: Form Pindah Hosting

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#109]
Pada saat uji coba unggah folder desa, database opensid premium dan pbb dengan masing-masing ukuran file yang besar kemudian ketika klik tombol ya untuk melakukan Unggah data terjadi error bahwa file masih dalam keadaan kosong harus dipilih kembali.

Berdasarkan penelusuran  pengecekan ukuran maksimal yang ada di validasi laravel atau livewire atau php.ini semua sudah berukuran sekitar 100 MB,

kemudian setelah diamati kondisi unggah data terkadang bisa dieksekusi dan terkadang gagal.

Diperbolehkan hanya unggah salah satu file.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/98
