### ISSUE TITLE
Dashboard: API pelanggan SaaS baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#11]
Sediakan API untuk dipanggil oleh Layanan untuk membuat pelanggan SaaS baru. Layanan akan mengirim info yg diperlukan. Dashboard akan melakukan setup awal pengguan OpenSID SaaS di server ybs. 

Yang dihasilkan termasuk:

1. Pemasangan OpenSID Umum/Premium: pembuatan database, folder desa, setup config (kode desa, token layanan, database), symlink
2. Pemasangan OpenSID API: email, ftp, symlink, dsbnya
3. Pemasangan PBB: pembuatan database, setup config, symlink, dsbnya

**Comment by scqolbu24** [comment]
1. Pemasangan OpenSID Umum/Premium: 
- [x] pembuatan database, 
- [x] folder desa, 
- [x] setup config (kode desa, token layanan, database), 
- [x] symlink

2. Pemasangan OpenSID API: 
- [x] install api
- [x] email, 
- [x] ftp, 
- [x] symlink,
- [x] dsbnya

4. Pemasangan PBB: 
- [x] pembuatan database, 
- [x] setup config, 
- [x] symlink, 
- [x] dsbnya

**Comment by FirlianiF** [comment]
Poin 1 sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/13

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/24
