### ISSUE TITLE
Data Pelanggan ditampilkan data yang terbaru

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#110]
- [x] Data Pelanggan ditampilkan data yang terbaru.
- [x] Ketika Tidak ada Backup tombol unduh database non aktif
- [x] Ketika Tidak ada Backup tombol mundur versi non aktif 
- [x] Warna tombol dibedakan warnanya

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/97
