### ISSUE TITLE
Sediakan API pembaruan token.

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#113]
Pada Layanan ketika ada perubahan akan merubah token sehingga perlu disediakan adanya penyesuaian di SiapPakai untuk pembaruan token di semua aplikasi. 

- [x] Sediakan API pembaruan token.
- [ ] Sediakan tombol pembaruan di SiapPakai.
- [ ] Sediakan tombol pembaruan secara masal (checklist).

**Comment by scqolbu24** [comment]
Dibuatkan issue terpisah:
- [ ] Sediakan tombol pembaruan di SiapPakai.
- [ ] Sediakan tombol pembaruan secara masal (checklist).

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/100
