### ISSUE TITLE
Tema dari pindah hosting tidak dapat diakses

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#115]
![error-tema](https://user-images.githubusercontent.com/68048807/197658534-b7d6a0c1-6e09-43d9-89c8-6a248e62baad.JPG)

**Comment by scqolbu24** [comment]
Setelah diuji coba, folder desa yang terbaca yang ada di master-opensid

**Comment by scqolbu24** [comment]
perbaikannya adalah `../../` diubah menjadi `../../../../multisite/kodedesa/` buat pada config.php

**Comment by scqolbu24** [comment]
Berdasarkan rapat tanggal 08 November, untuk tema berada di master semua, sehingga symlink tema ke folder desa di master.

- [x] Buat console symlink tema di folder desa master.
- [x] Panggil console symlink tema di instal master.

**Comment by eddieridwan** [comment]
Supaya jelas:

1. Jika menggunakan tema bawaan, yaitu Esensi, Natra, dan semua tema pro yg kita sediakan, maka desa tinggal memilih tema bawaan itu di pengaturan aplikasi
2. Jika meggunakan tema ubahan, maka desa terus saja menggunakan pilihan tema dari folder desa.

Jadi seharusnya tidak diperlukan perubahan apa2 untuk pilihan tema. Daftar tema pro yg kita sediakan seharusnya otomatis tersedia di pengaturan aplikasi. Yg perlu diperiksa mungkin pengaturan tema di folder desa (config.php atau lainnya) dapat diakses dengan benar.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/108
