### ISSUE TITLE
Konfigurasi FTP

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#117]
Referensi :
https://youtu.be/1WVBC0KBOeE
https://www.youtube.com/watch?v=FZRrlej5eco
https://youtu.be/GTC_yWub1ZU

**Comment by scqolbu24** [comment]
Panduan instal FTP: https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#instal-ftp

Revisi link
https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-ftp

**Comment by scqolbu24** [comment]
Refrensi FTP acces directory /var/www and directory homedir
https://www.youtube.com/watch?v=s6d5xb49BwE

**Comment by scqolbu24** [comment]
- [x] Sesuaikan env.example pada master OpenSID API
- [x] Tambahkan ftp_pass di config .env SiapPakai
- [x] Penyesuaian .env ketika Update Domain
- [x] Penyesuaian .env ketika Update Pelanggan

**Comment by FirlianiF** [comment]
Sudah dikerjaakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/107
