### ISSUE TITLE
Dashboard: API pelanggan Premium baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#12]
Sediakan API untuk dipanggil oleh Layanan untuk mengubah status versi OpenSID yg digunakan pelanggan SaaS menjadi Premium aktif, dari versi Umum atau Premium tidak aktif. Layanan akan mengirim info yg diperlukan. 

Dashboard akan melakukan:

1. update status site ybs
2. mengubah symlink site ybs mengarah ke P

**Comment by scqolbu24** [comment]
sudah diterapkan pada saat menjalankan API = {{host}}/api/newsite

**Comment by apidong** [comment]
sudah diperbaiki https://github.com/OpenSID/dashboard-saas/pull/18
