### ISSUE TITLE
Membatalkan Langganan SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#121]
- [x] Buat API batalkan / hapus pelanggan
- [x] Hapus data pelanggan
- [x] Hapus folder pelanggan
- [x] Hapus Database OpenSID
- [x] Hapus Database PBB
- [x] Hapus Username
- [x] Hapus domain pelanggan
- [x] Hapus SSL pelanggan

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/103
