### ISSUE TITLE
Status SSL dan Generate SSL

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#123]
Pada saat pendaftaran pelanggan Siap Pakai terjadi kasus bahwasanya SSL tidak tergenerate otomatis, sudah 2 desa yang mengalami hal tersebut.

Solusi untuk kasus ini sementara adalah digenerate manual pada panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/dokumentasi#pendaftaran-pelanggan

Untuk pelanggan yang kedua tetap gagal, setelah ditelusuri bahwa nama domain yang didaftarkan belum diarahkan ke server SiapPakai.

![gagal generate ssl](https://user-images.githubusercontent.com/68048807/200430845-efc3743d-77b5-411d-bd76-9b02e392bfea.JPG)

Harapannya dari issue ini dibuatkan kolom status SSL pada daftar pelanggan, kemudian terdapat  tombol untuk melakukan generate SSL. 

status dan tombol dapat dijadikan menjadi satu, tombol Hijau SSL sudah aktif, tombol merah status SSL belum aktif.
Jika klik status yang sedang aktif yaitu tombol hijau, maka akan mengapus SSL.    
Jika klik status yang sedang tidak aktif yaitu tombol merah, maka akan generate SSL.

**Comment by scqolbu24** [comment]
Dibuatkan pengecekan pada Layanan bahwa domain sudah diarahkan ke server VPS Siappakai atau belum

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/106
