### ISSUE TITLE
Notifikasi berhasil pembuatan website baru berbahasa Indonesia

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#124]
saat ini jika pertama kali di daftarkan pesan menggunakan bahasa inggris, yaitu:`new site generate in bakgroun job`, sebaiknya dibuat menggunakan bahasa indonesia.

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/105
