### ISSUE TITLE
Filter data pelanggan hanya berfungsi 1 kali

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#125]
Jika filter data pelanggan hany bisa dilakukan 1 kali saja, setelah dicek terdapat error seperti berikut:
![bug-dasbor-saas](https://user-images.githubusercontent.com/68048807/202045026-f7e921be-38f1-4758-be22-789966ed25a6.JPG)

**Comment by scqolbu24** [comment]
solusi https://laravel-livewire.com/docs/2.x/nesting-components

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/110
