### ISSUE TITLE
Perintah Queue cukup dijalankan sekali tidak berulang

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#126]
![berulang 3 kali-1](https://user-images.githubusercontent.com/68048807/202106782-9e207631-a9bb-438b-8465-f7f0059ddf70.JPG)

![berulang 3 kali](https://user-images.githubusercontent.com/68048807/202106971-3cb513d5-f572-4914-897f-81cef4e0dfb5.JPG)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/111
