### ISSUE TITLE
BUG: Update Rilis Rev

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#127]
Bug yang ditemukan ketika update rilis rev:

- [x] Folder desa pada master-opensid/premium tidak ada (tidak berhasil copy)
- [x] Folder desa pada masing pelanggan tidak tersalin dikarenakan permission folder folder-desa pada backup

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/112
