### ISSUE TITLE
Install modul ioncube untuk mendukung tema denatra

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#128]
Ketika desa menggunakan tema denatra terjadi error seperti berikut:
![erro pasuruan](https://user-images.githubusercontent.com/68048807/202326102-b9c66506-1616-44ab-96ac-75c9692eb543.JPG)

**Comment by scqolbu24** [comment]
Panduan: https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#instal-ioncube

**Comment by FirlianiF** [comment]
Sudah tersedia cara mengatasi nya pada panduan diatas.
