### ISSUE TITLE
Dashboard: API perpanjang langganan Premium

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#13]
Sediakan API untuk dipanggil oleh Layanan untuk mengubah tgl berakhir pelanggan SaaS Premium aktif. Layanan akan mengirim info yg diperlukan.

Dashboard akan melakukan:

1. update status site ybs

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui https://github.com/OpenSID/dashboard-saas/pull/15
