### ISSUE TITLE
Multiple PHP

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-siappakai#131]
Beberapa aplikasi akan diupdate ke laravel 9 menggunakan php 8. maka dibutuhkan multiple php dan pengaturannya dimasukan ke .httaccess

**Comment by apidong** [comment]
sudah dibuatkan panduan di 
https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi/server-vps#instal-phpmyadmin

**Comment by scqolbu24** [comment]
Yang perlu dilengkapi pada extension di php 8 : 
![extension](https://user-images.githubusercontent.com/68048807/207480742-9fff1556-bb71-4ab2-9b00-5bb4d358a9a4.JPG)

Setelah jalankan perintah berhasil lakukan composer update, perintah tersebut ada pada panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi/server-vps#update-ke-multiple-php pada poin 3 yaitu:
sudo apt install php8.1 php8.1-fpm libapache2-mod-php8.1 php8.1-curl php8.1-intl php8.1-zip php8.1-soap php8.1-xml php8.1-gd php8.1-mbstring php8.1-bcmath php8.1-common php8.1-xml php8.1-mysqli php8.1-tidy -y

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi/server-vps#pembaruan-multi-php
