### ISSUE TITLE
Logo mitra tidak tampil

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#133]
logo mitra pada halaman web opensid tidak tampil, dalam hal ini contohnya adalah IDCH

**Comment by scqolbu24** [comment]
solusinya:
- [x] buat API untuk mitra pada newsite
- [x] buat perintah php artisan opensid:mitra
       isinya menjalankan sudo touch mitra di pelanggan yang akan membuat file dengan nama mitra
- [x] setiap memilih server jenis idch pada layanan maka ketika newsite akan memanggil perintah php artisan opensid:mitra
- [x] untuk yang sudah terdaftar di pelanggan select data pelanggan terlebih dahulu ketika menjalankan perintah php artisan opensid:mitra atau perintah php artisan opensid:mitra --kode_desa={}

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/138
