### ISSUE TITLE
Pelanggan yang menggunakan tema pro tidak dapat diakses ketika update rilis 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#140]
Issue ini terjadi yang disebabkan karena folder desa tidak direstore yang ada pada master-opensid/premium, sehingga tema-tema pro yang ada pada folder desa kosong.

**Comment by scqolbu24** [comment]
issue ini sudah dapat berjalan dengan baik dengan perbaikan pada PR https://github.com/OpenSID/dashboard-saas/pull/121

**Comment by scqolbu24** [comment]
untuk rev-01 masih belum berfungsi, setelah dicek dikarenakan directory premium tidak dapat di rename ke premium_rilis

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/143
