### ISSUE TITLE
Tambahkan .htaccess pada SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#143]
Pada SiapPakai rilis 23.01.01 perlu ditambahkan pada .htaccess untuk memilih versi php, jika tidak akan terjadi eror seperti berikut :

![htaccess pada siappakai](https://user-images.githubusercontent.com/68048807/210460758-271ca1d3-ed2b-4517-94c6-66ccd3af85ab.JPG)

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/127
