### ISSUE TITLE
Pengaturan Aplikasi SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#145]
- [x] Sediakan perintah untuk mengaktifkan atau menon aktifkan fitur SiapPakai Kab melalui perintah command.
- [x] Migrasi table pengaturan
- [x] Seeder Pengaturan Aplikasi
- [x] Setting Image
- [x] Halaman Pengaturan
a. Pilih Kabupaten/Kota
b. Ubah Logo
c. Ubah Ubah Favicon
d. Sebutan Kota/Kabupaten

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/148
