### ISSUE TITLE
Halaman untuk mendaftarkan Data Desa (generate newsite)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#147]
Halaman ini berdasarkan penambahan data pelanggan opensid yang ada di Layanan.
Ketika memilih desa berdasarkan desa yang sudah terdaftar di layananan saja yang akan ditampilkan pada pilihan desa.

Untuk Data desa berdasarkan verifikasi token dan kode desa yang sudah terdaftar di Layanan maka akan dilanjutkan proses generate.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/158
