### ISSUE TITLE
Halaman untuk menambahkan tema pro, aktivasi dan konfigurasinya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#148]
Halaman ini mengikut penambahan tema pro yang ada di Layanan. 

apakah tema menyesuaikan dengan yang sudah ada sekarang atau custom per masing-masing kabupaten ?

Dalam satu kabupaten/kota menggunakan tema yang sama dengan tema cutom.

**Comment by scqolbu24** [comment]
- [x] https://github.com/OpenSID/wiki-layanan-opendesa/issues/281

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/186
