### ISSUE TITLE
Kesalahan Url Master OpenSID Premium pada sidebar 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#149]
Kesalahan url pada sidebar
![url opensid](https://user-images.githubusercontent.com/68048807/210575454-59240f74-e6ae-485c-9284-111af22b3570.JPG)

Seharusnya https://siappakai2.opendesa.id/opensid-premium seperti yang ada di dasbor.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/137
