### ISSUE TITLE
Sediakan VPS production pertama

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#15]
Sediakan VPS OpenSID SaaS production pertama. 

Siapkan sebelum Layanan OpenSID SaaS dibuka. 

Yang dipasang termasuk:

1. OpenSID Premium terkini sampai 5 bulan sebelumnya
2. OpenSID Umum
3. OpenSID API
4. PBB

**Comment by scqolbu24** [comment]
sudah dikerjakan VPS production https://siappakai1.opendesa.id

**Comment by vickyrolanda** [comment]
sudah dikerjakan VPS production https://siappakai1.opendesa.id/
