### ISSUE TITLE
BUG: Tema tidak dapat update otomatis

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#151]
Ketika replikasi issue https://github.com/OpenSID/wiki-saas/issues/135 bahwasanya untuk tema batuah sudah update, namun dicek di aplikasi OpenSID yang menggunakan tema batuah belum update terbaru, sehingga dicek menggunakan perintah manual dan terdapat eror, harapannya tema dapat update secara otomatis dengan normal.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/140
