### ISSUE TITLE
Sediakan tombol pembaruan di SiapPakai.

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#156]
- [x] Pembaruan di database
- [x] PembaruanTokenJob melalui Layanan dan OpenKab
- [x] Pembaruan pada config premium
- [x] Pembaruan pada env pbb
- [x] Pembaruan pada env api

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/156
