### ISSUE TITLE
BUG: data yang telah diinput pada modal pindah hosting ketika di close masih ada

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#158]
Data yang telah diinput pada modal pindah hosting ketika di close masih ada.

Cara replikasi:
1. Login pada aplikasi SiapPakai
2. Masuk ke halaman pelanggan 
3. Klik tombol `Pindah Hosting`
4. upload folder desa baik itu sesuai dengan ketentuan atatu tidak
5. Klik tombol `Batal`
6. Klik kembali tombol `Pindah Hosting`
7. Isian pada folder desa masih ada, seharusnya sudah tidak ada

![modal-pindah-hosting1](https://user-images.githubusercontent.com/68048807/213025237-85d08426-ba4f-4086-845f-a015b2c416be.JPG)
![modal-pindah-hosting2](https://user-images.githubusercontent.com/68048807/213025257-8fe8ab3e-6c6f-4927-ae2c-fd6ddedd95ba.JPG)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/145
