### ISSUE TITLE
Panduan teknis Dashboard-SaaS bagi programmer

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#16]
Buat panduan teknis Dashboard-SaaS bagi programmer. Termasuk arsitektur, API, proses pengembangan, rilis, dsbnya.

Letakkan di [panduan.opendesa.id](https://panduan.opendesa.id/), disertai penjelasan secukupnya.

**Comment by scqolbu24** [comment]
![struktur folder saas](https://user-images.githubusercontent.com/68048807/186561089-1f43ce98-f731-4d11-a619-478806fd75fe.JPG)
![struktur folder saas1](https://user-images.githubusercontent.com/68048807/186561100-9e26c5f1-da97-4e9b-90db-63d067522698.JPG)
![struktur folder saas2](https://user-images.githubusercontent.com/68048807/186561106-800ba672-3189-478f-9ce0-eeb6062e30b1.JPG)

**Comment by scqolbu24** [comment]
![perintah-perintah](https://user-images.githubusercontent.com/68048807/192286180-4a0f0ffa-0f60-4833-a47d-8e24986e7214.JPG)

**Comment by vickyrolanda** [comment]
mas @devrakapriyo  mohon dibantu di review ya mas.

**Comment by devrakapriyo** [comment]
baik mas @vickyrolanda 

mas @scqolbu24 apakah dokumentasinya masih proses pembuatan? atau sudah ada?
