### ISSUE TITLE
Composer detected pada aplikasi SiapPakai, PBB dan API

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#162]
Jika menggunakan multi PHP dan defaultnya adalah PHP 8 maka pada httaccess tidak perlu script berikut 
```
<FilesMatch \.php$>
         # 2.4.10+ can proxy to unix socket
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
</FilesMatch>
```
Jika terdapat script diatas maka akan error seperti berikut:
![composer detected](https://user-images.githubusercontent.com/68048807/213337725-365c5c9e-a8d7-4fe1-bbfe-109b315a3df4.JPG)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/144

**Comment by scqolbu24** [comment]
Pada issue ini ketika sudah upgrade ke laravel 9 dan agar opensid tetap berjalan sehingga maka default PHP adalah 7.4 kemudian untuk htaccess disesuaikan antara PHP 7.4 atau 8.1 sesuai dengan kebutuhan masing-masing aplikasi.
a. OpenSID menggunakah PHP 7.4
b. SiapPakai, PBB, API menggunakah 8.1

kemudian jika masih terdapat error  seperti berikut:
![composer detected](https://user-images.githubusercontent.com/68048807/213337725-365c5c9e-a8d7-4fe1-bbfe-109b315a3df4.JPG)

maka yang perlu dilakukan adalah:
1. Cek versi default PHP pastikan menggunakan 7.4 agar dapat digunakan oleh OpenSID cek pada `phpinfo.php`
2. Cek pada terminal pastikan menggunakan PHP 8.1
3. Pastikan status PHP 7.4 berjalan dengan normal cek dengan perintah `sudo systemctl status php7.4-fpm`
```Output:
php7.4-fpm.service - The PHP 7.4 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php7.4-fpm.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-06-05 11:25:07 UTC; 1min 38s ago
       Docs: man:php-fpm7.4(8)
   Main PID: 13703 (php-fpm7.4)
     Status: "Processes active: 0, idle: 2, Requests: 0, slow: 0, Traffic: 0req/sec"
      Tasks: 3 (limit: 2353)
     Memory: 6.2M
     CGroup: /system.slice/php7.4-fpm.service
             ├─13703 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
             ├─13719 php-fpm: pool www
             └─13720 php-fpm: pool www
```
4. Pastikan status PHP 8.1 berjalan dengan normal `sudo systemctl status php8.1-fpm`
```Output
● php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-06-05 11:25:07 UTC; 1min 38s ago
       Docs: man:php-fpm8.1(8)
   Main PID: 13703 (php-fpm8.1)
     Status: "Processes active: 0, idle: 2, Requests: 0, slow: 0, Traffic: 0req/sec"
      Tasks: 3 (limit: 2353)
     Memory: 6.2M
     CGroup: /system.slice/php8.1-fpm.service
             ├─13703 php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)
             ├─13719 php-fpm: pool www
             └─13720 php-fpm: pool www
```
5. Jika pada poin 4 mengalami kegagalan 'failed'
![failed php 8 1](https://user-images.githubusercontent.com/68048807/214477501-d0f8332e-bc88-477e-92c8-ddfdffed4c74.jpg)
Maka untuk perbaikannya ikuti langkah berikut:
a. Hapus semua PHP 8.1 
```
sudo apt purge -y php8.1*
```
b.   Install ulang
```
sudo apt install php8.1 php8.1-fpm libapache2-mod-php8.1 php8.1-curl php8.1-intl php8.1-zip php8.1-soap php8.1-xml php8.1-gd php8.1-mbstring php8.1-bcmath php8.1-common php8.1-xml php8.1-mysqli php8.1-tidy -y
```
c. Jalankan PHP 8.1 
```
sudo systemctl start php8.1-fpm
```
d. Cek Status PHP 8.1
```
sudo systemctl status php8.1-fpm
```
6. Tambahkan *script* pada `file htaccess` disesuaikan antara PHP 7.4 atau 8.1 sesuai dengan kebutuhan masing-masing aplikasi.
```
<FilesMatch \.php$>
         # 2.4.10+ can proxy to unix socket
        SetHandler "proxy:unix:/run/php/php7.4-fpm.sock|fcgi://localhost"
</FilesMatch>
```
atau
```
<FilesMatch \.php$>
         # 2.4.10+ can proxy to unix socket
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
</FilesMatch>
```

**Composer yang digunakan pada aplikasi tertentu**
Jika Aplikasi agar dapat menggunakan composer PHP 7.4 maka jalankan perintah
```
/usr/bin/php7.4 /usr/local/bin/composer update
```
Jika Aplikasi akan menggunakan composer PHP 8.1 maka jalankan perintah
```
composer update
```

**Comment by scqolbu24** [comment]
sudah dibuatkan panduan pada https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/dokumentasi#versi-multi-php

PR https://github.com/OpenSID/dashboard-saas/pull/144 tidak digunakan sehingga dirubah kembali pada PR https://github.com/OpenSID/dashboard-saas/pull/148
