### ISSUE TITLE
Penentuan installasi awal pada OpenSaas untuk  SiappakaiKab

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#163]
1. Pada perses install OpenSID maka perlu ada kondisi untuk menentukan apakah seeder perlu di jalankan atau tidak dengan melihat jumlah desa atau check database apakah sudah tersedia. 

Issue ini mungkin perlu penjelasan / diskusi kembali.

**Comment by scqolbu24** [comment]
1. Instalasi awal untuk pelanggan SiapPakai OpenKab untuk menentukan nama database berdasarkan kota/kabupaten tertentu dan pertama kali yang di seeder. 
2. Dibuat Kondisi untuk pemeriksaan desa pertama atau desa kedua (dan seterusnya) agar menentukan database yang digunakan di awal.
3. berkaitan dengan issue https://github.com/OpenSID/wiki-saas/issues/147 untuk generate pelanggan/desa/kelurahan.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/160
