### ISSUE TITLE
Tidak dapat update versi SiapPakai 23.01.02 ke 23.01.03

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#164]
Pada Update SiapPakai versi v23.01.02 tidak dapat update ke v23.01.03 secara otomatis.

setelah dilakukan pengetesan secara manual terdapat pesan eror bahwa ada perubahan sebelumnya yang tidak di commit secara otomatis sehingga mengakibatkan perintah update tidak dapat di eksekusi. 

solusinya dalah menambahkan perintah commit secara otomatis terlebih dahulu.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/147
