### ISSUE TITLE
Penyesuaian config:app untuk OpenKab

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#165]
Pada file .env SiapPakai untuk OpenKab terdapat penambahan sehingga untuk config:app perlu adanya penyesuaian diantaranya:

- [x] FTP_USER
- [x] OPENKAB

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/154
