### ISSUE TITLE
BUG: aplikasi pbb pada masing-masing pelanggan setelah rilis v23.02.01 mengalami eror

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#168]
Setelah dicek secara manual pada salah satu desa, dengan menjalankan `sudo composer update` dapat berjalan dengan normal
kemudian setelah dicek pada source code perlu ditambahkan pada perintah tersebut di masing-masing pelanggan pada File UpdatePbb setelah baris 188.

**Comment by apidong** [comment]
@scqolbu24 perlu di cek juga, owner dari folder aplikasi pbb apakah root dan juga permision dari folder vendor. 
karena composer update seharusnya bisa jalan tanpa akses root.

**Comment by scqolbu24** [comment]
> @scqolbu24 perlu di cek juga, owner dari folder aplikasi pbb apakah root dan juga permision dari folder vendor. karena composer update seharusnya bisa jalan tanpa akses root.

sudah dicek mas @apidong, pada update per masing-masing pelanggan belum ada perintah composer update

**Comment by FirlianiF** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/dashboard-saas/pull/152
