### ISSUE TITLE
BUG: API pada masing-masing pelanggan setelah rilis v23.02.01 mengalami eror

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#169]
Setelah dicek secara manual pada salah satu desa, dengan menjalankan `sudo composer update` dapat berjalan dengan normal
kemudian setelah dicek pada source code perlu ditambahkan pada perintah tersebut di masing-masing pelanggan pada File UpdateApi setelah baris 188.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/153
