### ISSUE TITLE
Panduan penggunaan Dashboard-SaaS bagi pelaksana

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#17]
Buat panduan Dashboard-SaaS bagi pelaksana. Termasuk pengelolaan tiket Help Desk, memasang tema pro, tema desa, template surat desa, widget desa, proses manual memasang/menyesuaikan/menghapus site dsbnya.

Letakkan di [panduan.opendesa.id](https://panduan.opendesa.id/), disertai penjelasan secukupnya.

**Comment by scqolbu24** [comment]
Berdasarkan Rapat pertemuan 14 Juli 2022 :

- [x] 1. Dibuatkan flowchart di layanan mengenai langkah-langkah pemesanan dashboard saas 
           https://github.com/OpenSID/wiki-layanan-opendesa/issues/124
- [x] 2. Penamaan Layanan Saas adalah OpenSID Saas.
           https://github.com/OpenSID/wiki-layanan-opendesa/issues/123

**Comment by scqolbu24** [comment]
Panduan Yang sudah dikerjakan:

- [x] Instalasi --> https://panduan.opendesa.id/id/dasbor-saas/instalasi
- [x] Memperbarui --> https://panduan.opendesa.id/id/dasbor-saas/memperbarui
- [x] Rilis --> https://panduan.opendesa.id/id/dasbor-saas/rilis
- [x] Halaman Administrasi --> https://panduan.opendesa.id/id/dasbor-saas/halaman-administrasi

**Comment by scqolbu24** [comment]
![eror ketika sudah ada db_saas_dashboard](https://user-images.githubusercontent.com/68048807/181867417-06c1e355-47c0-4c44-941c-6958c973eb28.JPG)

**Comment by scqolbu24** [comment]
Berikut halaman administrasi untuk panduan:

![halaman login](https://user-images.githubusercontent.com/68048807/184148289-e093fce8-7b92-4023-970b-fa87c480f50f.JPG)

![dasbor-saas2](https://user-images.githubusercontent.com/68048807/184468078-5a7e0915-2a18-4827-a433-d2e15e0bccea.jpg)

![tema-pro1](https://user-images.githubusercontent.com/68048807/184322343-6f80cec7-5d4b-4816-bc71-af0d68f7ca10.jpg)

![informasi](https://user-images.githubusercontent.com/68048807/184364647-3f0fafba-dbb5-4127-9dc2-d47c2464a3c9.JPG)

![pelanggan-fix](https://user-images.githubusercontent.com/68048807/184468673-e04506a6-fff6-476b-8d02-47479a945fbe.jpg)

![queuemonitor](https://user-images.githubusercontent.com/68048807/184370278-5620224a-473e-4d59-8963-e202ae474cd2.jpg)

**Comment by devrakapriyo** [comment]
sudah ok mas
