### ISSUE TITLE
BUG: Tema Denava tidak update secara otomatis

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#171]
Tema Denava sudah versi 4.0, namun pada pelanggan di siappakai tema masih versi 2.2, berikut tangkapan layar.
![tema denava-bug](https://user-images.githubusercontent.com/68048807/217409811-fc8d909b-2e11-4662-a3d7-eb3258570fba.JPG)

Seteah dicek menggunakan manual terdapat conflict seperti tangkapan berikut :
![tema denava-conflict](https://user-images.githubusercontent.com/68048807/217410182-b35b1b39-1101-4558-8b7c-7b5a5029933a.JPG)

Saran dari Pak Ariandi, sebaiknya menggunakan perintah `git fetch` untuk menghindari terjadinya conflict. 

dan tambahkan git config global untuk safe.directory, user.name dan user.email

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/161
