### ISSUE TITLE
BUG: Authentication Server SiapPakai (Penyesuaian Laravel 9)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#172]
Pada saat testing Pembaruan Token di server local pada Issue https://github.com/OpenSID/wiki-saas/issues/156, ditemukan bug yaitu tidak dapat melakukan pendaftaran akun pada database siappakai yang akan digunakan dapat dilihat pada tangkapan layar berikut:

![registerauth](https://user-images.githubusercontent.com/68048807/217514713-74e1ca2b-4d4f-4983-ace3-8f630169b1a6.png)

Setelah dibandingkan pada table personal_access_tokens pada laravel 8 dan laravel 9 terdapat penambahan kolom `expires_at`, sehingga perlu ditambahkan kolom tersebut dari hasil upgrade [laravel 9](https://github.com/OpenSID/wiki-saas/issues/144).

![registerauth1](https://user-images.githubusercontent.com/68048807/217521974-b766cdf8-9eff-4a65-bb5f-2555202b0736.png)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/157
