### ISSUE TITLE
Dashboard: Buat Tampilan Awal (Template UI OpenSID Saas)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#18]
Sebagai tampilan ui diperlukan instalasi template dengan blade sehingga dapat mempermudah pengelolaan pada aplikasi OpenSID Saas.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/2
