### ISSUE TITLE
Sediakan tombol Unduh folder Desa pada SiapPakai dan kebutuhan OpenKab

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#183]
Saat ini pelanggan SiapPakai terbagi menjadi 2 server, sebaiknya digabungkan menjadi 1 server sehingga mudah pengelolaannya, kemudian untuk proses pemindahannya adalah dibutuhkan backup database dan folder desa, saat ini baru tersedia unduh database, maka dari itu perlu disediakannya tombol untuk unduh folder desa.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/163
