### ISSUE TITLE
Lakukan penerapan berdasarkan pengaturan tema bawaan setiap tambah desa

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#185]

**Comment by scqolbu24** [comment]
Tahapan issue yang dikerjakan :

- [x] https://github.com/OpenSID/OpenSID/issues/6498
- [x] https://github.com/OpenSID/wiki-saas/issues/184
- [x] Simpan Tema berdasarkan tema bawaan yang akan diinstall
- [x] Penyesuaian desa/config/config.php untuk pengaturan web_theme (jika openkab dan pengaturan sesuai)
- [x] Install tema ke master-tema-pro (diinstall ketika klik simpan pada pengaturan aplikasi)
- [x] copy folder tema ke theme di folder desa pada master-opensid/premium (diinstall ketika klik simpan pada pengaturan aplikasi)
- [x] buat symlink tema web theme ke folder desa masing-masing

**Comment by vickyrolanda** [comment]
> [ ] copy folder tema ke theme di folder desa pada master-opensid/premium (diinstall ketika klik simpan pada pengaturan aplikasi)

bagian ini : 
 copy folder tema ke theme di folder desa pada master-opensid/premium (diinstall ketika klik simpan pada pengaturan aplikasi)
 
maksudnya gmna itumas.

**Comment by scqolbu24** [comment]
> > [ ] copy folder tema ke theme di folder desa pada master-opensid/premium (diinstall ketika klik simpan pada pengaturan aplikasi)
> 
> bagian ini : copy folder tema ke theme di folder desa pada master-opensid/premium (diinstall ketika klik simpan pada pengaturan aplikasi)
> 
> maksudnya gmna itumas.

bagian ini folder tema-bima yang sudah diinstall akan di copy ke master-opensid/premium seperti yang sudah diterapkan di tema pro yang lainnya, jika disini tidak ada maka tema tidak akan berjalan.

revisi bukan copy melainkan symlink.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/175
