### ISSUE TITLE
BUG: Perintah job dan Command tidak berjalan ketika ada penambahan baru

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#186]
Ketika terdapat penamabahan perintah baru pada command dan jobs tidak berjalan, dapat dilihat melalui monitoring jobs pada tampilan berikut:

![job dan perintah command tidak berjalan](https://user-images.githubusercontent.com/68048807/223360282-0b046cad-35ad-46fb-a6a4-5a20774cd3d3.JPG)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/164
