### ISSUE TITLE
Bug : Validasi Login pada SiapPakai muncul peringatan  Koneksi Database Gagal

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#192]
issue ini muncul setelah upgrade ke laravel 9.
ketika akan login dengan salah username atau password akan muncul error  Koneksi Database Gagal, setelah dicek koneksi database sesuai sesuai konfigurasi pada env. 

Seharusnya eror muncul dengan peringatan username atau password yang dimasukan salah.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/172
