### ISSUE TITLE
BUG: validasi ketika pilih kabupaten pada pengaturan aplikasi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#193]
![validasi pilih kabupaten ketika kosong](https://user-images.githubusercontent.com/68048807/224604691-53890649-0674-42c7-a3ce-4bbbfa3d4e85.JPG)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/174
