### ISSUE TITLE
Pasang PBB di VPS development

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#20]
Karena OpenSID SaaS bersifat siap pakai dan tidak ada akses cPanel, maka semua aplikasi yang disediakan bagi pelanggan premium juga perlu disediakan siap pakai.

Yaitu PBB perlu disediakan supaya pengguna premium siap menggunakan aplikasi PBB.

Karena aplikasi PBB bisa berubah sesuai dengan kebutuhan masing2 versi OpenSID Premium, maka di server SaaS perlu juga dipasang versi PBB sesuai dengan ke-5 versi Premium yg terpasang.

**Comment by scqolbu24** [comment]
sudah diinstal di DevSaas.
Pemasangan PBB: 
- [x] pembuatan database, 
- [x] setup config, 
- [x] symlink, 

http://103.172.204.47/pbb

**Comment by FirlianiF** [comment]
Database sudah berdiri pada masing-masing desa.
https://devsaas.opendesa.id/desasatu-pbb
https://devsaas.opendesa.id/desadua-pbb
https://devsaas.opendesa.id/desatiga-pbb
