### ISSUE TITLE
Hilangkan Data Desa yang sudah terpasang pada menu tambah desa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#207]
- [x] Buat Migrasi tabel data desa
- [x] Buat Model
- [x] Ambil Data Desa ke pantau melalui pengaturan dan simpan ke db.
- [x] Cek Jika sudah ada pelanggan yang terdaftar maka ubah status menjadi terdaftar pada tabel desa.
- [x] Hapus data desa jika pada pengaturan beda kabupaten/kota
- [x] Buatkan API untuk menampilkan data desa pada pilihan tambah desa
- [x] Filter data desa dengan status belum terdaftar
- [x] Build Site OpenKab setiap melakukan pendaftaran desa ubah status.
- [x] Jika diubah pada pengaturan maka hapus terlebih dahulu data lama dan diubah data baru
- [x] Cek Jika sudah ada pelanggan yang terdaftar maka ubah status menjadi terdaftar pada tabel desa.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/277
