### ISSUE TITLE
Pasang OpenSID API di VPS development

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#21]
Karena OpenSID SaaS bersifat siap pakai dan tidak ada akses cPanel, maka semua aplikasi yang disediakan bagi pelanggan premium juga perlu disediakan siap pakai.

Yaitu OpenSID API perlu disediakan supaya pengguna premium siap menggunakan aplikasi mobile.

Karena OpenSID API bisa berubah sesuai dengan kebutuhan masing2 versi OpenSID Premium, maka di server SaaS perlu juga dipasang versi OpenSID API sesuai dengan ke-5 versi Premium yg terpasang.

**Comment by scqolbu24** [comment]
Pemasangan OpenSID API: 
- [x] install api
- [x] email, 
- [x] ftp, 
- [x] symlink,
- [x] dsbnya

http://103.172.204.47/api/
http://103.172.204.47/api/healthcheck

**Comment by FirlianiF** [comment]
Database sudah berdiri pada masing-masing desa.
https://devsaas.opendesa.id/desasatu-api
https://devsaas.opendesa.id/desadua-api
https://devsaas.opendesa.id/desatiga-api
