### ISSUE TITLE
Penyesuaian pembuatan user ketika generate newsite (opensid, pbb)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#211]
issue ini berkaitan dengan issue https://github.com/OpenSID/wiki-saas/issues/210,

ketika newsite pada siappakai dari layanan dan dari siappakai untuk database gabungan dapat berjalan normal, namun ketika dites pada server yang terpisah antara server database dan server source code, database seeder tidak dapat dijalankan, setelah dicek manual terdapat muncul pesan bahwa ip yang digunakan harus dari server database.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/184
