### ISSUE TITLE
BUG: Secret is not set pada OpenSID API

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#212]
![photo_2023-03-28_21-58-42](https://user-images.githubusercontent.com/68048807/228280409-cf488c76-a3f2-4d7c-adad-fbf5720dc5dc.jpg)

pada error tersebut setelah dicek di log error muncul pesan eror Secret is not set, sehingga perlu jalankan phpartisan jwt:secret

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/187
