### ISSUE TITLE
ubah penamaan kabupaten pada pilihan tambah desa dan hapus penamaan kota yang duplikat

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#213]
![2023-03-30_22h09_57](https://user-images.githubusercontent.com/68048807/228881917-3f6efeeb-d224-401f-ade5-ee5be813d027.png)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/189
