### ISSUE TITLE
Penyesuaian vhost di pada saat install siappakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#218]
pada saat instalasi jika menggunakan proxy seperti yang diterapkan di kota bima, maka perlu menonaktifkan atau menghapus script yang berkaitan dengan apache.

**Comment by scqolbu24** [comment]
cara instalasi pada panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#instal-opensid-siappakai poin 5

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/193
