### ISSUE TITLE
Penyesuaian vhost di pada saat daftarkan desa baru

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#219]
- [x] Penambahan input port pada halaman daftar desa.
- [x] buildsitejob
- [x] migration field port
- [x] menampilkan port pada table pelanggan
- [x] menghilangkan ssl pada table pelanggan
- [x] kondisi menampilkan port ketika pengaturan domain = proxy 
- [x] buildsiteopenkab

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/196
