### ISSUE TITLE
Panggil Dashboard SaaS dari Layanan untuk register saat pembuatan server baru

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-siappakai#22]
untuk generate token, jadi setiap server memiliki tokennya masing-masing, dan tidak perlu input manual di code

**Comment by FirlianiF** [comment]
.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/70
