### ISSUE TITLE
Hapus desa pada OpenKab SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#220]
- [x] Hapus data pda tabel pelanggan
- [x] Hapus folder desa
- [x] Hapus Vhost
- [x] Hapus SSL 
- [x] Hapus Database PBB
- [x] Hapus User Database
- [x] Hapus Firewall port

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/204
