### ISSUE TITLE
BUG: tampilan OpenSID pada server kota bima tidak dapat diakses ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#226]
![image](https://user-images.githubusercontent.com/68048807/230116902-7fa342f5-5dff-4918-9833-afdba28728b0.png)

Setelah dicek pada file.htacces dan menonaktifkan paksa ke https, tampilan tema tidak teratur
![image](https://user-images.githubusercontent.com/68048807/230116265-dfb9b190-10d7-4830-8fa6-1ada14f60d20.png)

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/197
