### ISSUE TITLE
BUG: tidak dapat update dikarenakan perubahan tags rilis

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#227]
Tidak dapat update rilis terbaru berupa versi rev, dikarenakan terdapat perubahan penamaan tags rilis.

![image](https://user-images.githubusercontent.com/68048807/230232280-d5df784b-70e2-4727-9f51-8b83d56586de.png)

![image](https://user-images.githubusercontent.com/68048807/230232229-1be2e9a1-ef58-472e-90b2-26952998db59.png)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/203
