### ISSUE TITLE
BUG: halaman API masih belum dapat diakses

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#228]
![image](https://user-images.githubusercontent.com/68048807/230406833-779b3827-7b04-426b-b364-eb420e229ad7.png)

belum bisa jalankan composer install dan app_key masih kosong dikarenakan database belum diarahkan ke database gabungan.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/199
