### ISSUE TITLE
BUG: Jika nama desa sama dengan nama database gabungan maka tidak dapat didaftarkan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#230]
<img width="921" alt="2023-04-10_14h36_21" src="https://user-images.githubusercontent.com/68048807/230852180-5a46d7ee-d80c-4f15-b2a6-9e5c1b7a763a.png">

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/202
