### ISSUE TITLE
Penamaan aplikasi SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#232]
- [x] Perbaiki penamaan aplikasi Siap Pakai menjadi SiapPakai. 
- [x] Perbaiki link ke panduan SiapPakai

**Comment by scqolbu24** [comment]
perli di konfirmasi untuk penamaanya yang digunakan yang mana?

- [ ] Dasbor SiapPakai mulai Desember 2022
- [ ] OpenSID SiapPakai 
- [ ] Layanan OpenSID SiapPakai

**Comment by scqolbu24** [comment]
Hasil dari pertemuan Hari Kamis, Tanggal 27 April 2023 penamaan aplikasi adalah Dasbor SiapPakai

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/211
