### ISSUE TITLE
Perintah pada Console opensid: diubah menjadi siappakai:

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#237]

**Comment by scqolbu24** [comment]
https://panduan.opendesa.id/id/dasbor-siappakai/dokumentasi#mengenal-perintah-dasbor-siappakai
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/2c6c5e44-689a-450a-b9c2-9a64fdfb7edc)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/222
