### ISSUE TITLE
Penyesuaian tema ketika pembaruan token

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#243]
![penyesuaian tema](https://user-images.githubusercontent.com/68048807/236653131-42510dc7-a3d1-42f2-8273-b9c72caea6b7.JPG)

**Comment by scqolbu24** [comment]
Arahan dari Pak Eddie : 
1. Dasbor SiapPakai dipasang di server Diskominfo Kota Bima, dan script tema dimuat di situ. Kelurahan yg terpasang di Dasbor SiapPakai Kota Bima hanya dari Kota Bima, tidak mungkin dari wilayah lain
2. Tema Kota Bima dipesan khusus dan diberikan kepada Kota Bima
3. Tidak ada kelurahan/desa lain yg berhak atau menggunakan Tema Kota Bima

Dengan pertimbangan seperti itu, sepertinya lebih cocok dan memudahkan, jika:

1. Tema Kota Bima otomatis terdaftar/tersedia bagi semua kelurahan yg terpasang di Dasbor SiapPakai, tanpa perlu memeriksa ke Layanan. Yaitu disamakan dengan tema bawaan
2. Tema Kota Bima tampil di OpenSID secara default jika itu yg diatur di Dasbor SiapPakai
3. Kelurahan Kota Bima dapat memilih tema lain. Jika memilih tema premium, maka harus ada kode aktivasinya seperti biasa

**Comment by scqolbu24** [comment]
Penerapannya mulai dari pertama kali mendaftarkan sudah diterapkan konfigurasi temanya, seperti aktivasi_tema kode_kota dll,
saat ini baru tersimpan tema default kota bima pada table tema, untuk table konfigurasi tema masih null.

opsi lain pada pembaruan token dibuat kondisi select tema melalui script.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/221
