### ISSUE TITLE
Blank ketika melakukan pencarian pada tabel pelanggan kemudian buka tombol aksi pembaruan token serta jalankan tombol Ya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#247]

**Comment by scqolbu24** [comment]
Sudah dikerjakan melalui Panduan:
https://panduan.opendesa.id/dasbor-siappakai/halaman-administrasi#pembaruan-token
https://panduan.opendesa.id/id/dasbor-siappakai/halaman-administrasi/database-gabungan#pembaruan-token

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/256
