### ISSUE TITLE
BUG: konfigurasi FTP di env API pada database gabungan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#249]
![Image](https://user-images.githubusercontent.com/68048807/238494233-97c34112-10e4-462c-8b13-b19234893acc.png)

Setelah dicek dikarenakan pada pendaftaran desa/keluarahan pada env di dashboard-saas belum diubah pada pengaturan ftp.
sesuai dengan panduan https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-dasbor-siappakai langkah nomor 8

`php artisan siappakai:config-ftp --ftp_pass=<password>`

Solusi yang perlu dilakukan sekarang adalah buat pengaturan untuk mengubah pengaturan env di semua API kelurahan yang sudah didaftarkan.

**Comment by scqolbu24** [comment]
issue ini dikerjakan setelah issue https://github.com/OpenSID/wiki-saas/issues/252

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/237
