### ISSUE TITLE
Penyesuaian jwt:secret

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#252]
Jika pada OpenSID API belum jalankan perintah `php artisan jwt:secret` maka aplikasi mobile mobile belum dapat digunakan dengan peringatan seperti berikut:
![WhatsApp Image 2023-05-17 at 06 12 15](https://github.com/OpenSID/wiki-saas/assets/68048807/d2fc477d-4ac2-4bcd-8ce2-6855e1f9aa7a)

**Comment by scqolbu24** [comment]
solusi dari issue ini adalah:
- [x] jalankan perintah pada saat instal di Dasbor SiapPakai database gabungan
- [x] jalankan perintah pada saat update API
- [x] jalankan perintah ketika update token premium

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/230
