### ISSUE TITLE
Terapkan fitur pengaturan email pada config opensid guna konfigurasi untuk lupa password

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#268]
- [x] Buat Migration 
- [x] Buat Modal Pengaturan
- [x] Simpan database
- [x] Pengaturan Email OpenSid Job
- [x] Ubah pada config/config.php

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/273
