### ISSUE TITLE
Struktur Folder

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#27]
Saat ini berdasarkan konsep awal struktur folder sebagai berikut:
![struktur](https://user-images.githubusercontent.com/68048807/173718716-b2a817a1-d8a5-4dd5-889d-7aff180551dd.jpg)

Dengan adanya penerapan PBB dan API di Dashboard Saas maka diperlukan penyesuaian struktur folder.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/10
