### ISSUE TITLE
Hapus file zip setelah selesai unduh folder desa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#274]
1. Saat ini jika melakukan unduh folder desa yaitu akan dibuatkan zip terlebih dahulu kemudian akan diunduh, 
2. namun proses klik tombol unduh folder desa harus dilakukan dua kali, yatu pertama proses persiapan file dibuat zip, kemudian kedua proses unduh,
3. sebaiknya setelah selesai diunduh file zip dihapus agar tidak terlalu banyak, sehingga tidak mengurangi memori server dan tombol unduh folder desa cukup dilakukan sekali atau diberi modal untuk tombol unduhnya.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/265
