### ISSUE TITLE
Penyesuaian ConfigEmail OpenSID

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#283]
Issue ini lanjutan dari issue https://github.com/OpenSID/wiki-saas/issues/268
penyesuaian config.php untuk ditambahakn config email, file yang berkaitan sebagai berikut:

- [x] Config Controller pada method configDesa()
- [x] Update Token Premium
- [x] Update Pelanggan
- [x] Update Tema Konfigurasi
- [x] Update Domain
- [x] Install Tema

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/276
