### ISSUE TITLE
BUG: notifikasi tgl_akhir_backup

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#285]
Testing Jika belum ada data pelanggan akan eror seperti berikut: 
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/569014e8-80d8-484d-9425-9fa68cd785da)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/278
