### ISSUE TITLE
BUG: table pelanggan eror pada versi_opensid

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#286]
Jika table pelanggan belum terdapat data, kemudian pada halaman pelanggan eror seperti berikut:
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/626894f5-18f5-4556-92f0-71f413b12723)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/279
