### ISSUE TITLE
Penyesuian file index.php dan buat pada helpers controller

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#287]
Saat ini untuk :

- [x] konfigurasi index.php OpenSID ada di file EnvController
- [x] konfigurasi index.php PBB ada di file BuildSite dan BuildSiteOpenKab
- [x] konfigurasi index.php API ada di file BuildSite dan BuildSiteOpenKab

Sebaiknya dibuatkan dalam satu file IndexController agar mudah dan lebih rapi serta akan digunakan ketika terjadi update dan dilakukan pengecekan tanggal akhir premium sehingga akan menyesuaian symlink yang akan digunakan.

File yang perlu disesuaiakan :

- [x] BuildSite
- [x] BuildsiteOpenKab
- [x] MundurVersi

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/281
