### ISSUE TITLE
Filter data desa ketika dilakukan pencarian pada saat akan melakukan pendaftaran

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#291]
Data Desa sebelumnya mengambil langsung dari pantau, dengan adanya perubahan fitur data desa yang diambil dari pantau disimpan terlebih dahulu di database dengan tujuan agar dapat memfilter data desa yang sudah terdaftar, namun muncul issue bahwa ketika dilakukan pencarian data desa tidak dapat di filter sehingga perlu adanya penyesuaian pada API.

Filter sebelumnya :
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/01f29465-f2fb-4926-a380-5db68b01ad06)

Setelah adanya perubahan:
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/311394b0-fe80-4254-910d-77a54c5b2b53)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/287
