### ISSUE TITLE
Penyesuaian Peringatan Git Token

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#292]
Peringatan Git token sering digunakan yaitu terdapat 12 result pada pencarian, sehingga perlu dibuat pada helper.
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/94847ed5-9072-4e01-84b9-8c24c4f7355e)

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/290
