### ISSUE TITLE
Penyesuaian Unlink Command

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#293]
Script Unlink command terdapat di beberapa tempat, sebaiknya dibuatkan helper untuk mempersingkat script dan ketika ada penambahan cukup dilakukan di helper tersebut tidak mengubah di beberapa tempat lagi, Adapun yang perlu diubah diantaranya:
- [x] Update OpenSID
- [x] Update PBB
- [x] Update API

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/292
