### ISSUE TITLE
Pada Aplikasi PBB yang berlangganan SiapPakai tidak dapat unduh contoh format excel SPPT

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#296]
Yang perlu diperbaiki adalah: 

- [x] master template pbb di file index
- [x] command controller UpdateIndex
- [x] Hapus file index yang lama
- [x] copy directory import
- [x] jalankan fileindex
- [x] Jalankan update index setelah update siappakai

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/294
