### ISSUE TITLE
backup otomatis ke google drive

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#298]
Penjelasan detail tentang issue ini : https://trello.com/c/iboDo4Ux/26-desa-pesayangan

**Comment by scqolbu24** [comment]
Panduan tentang penerpaan issue ini https://panduan.opendesa.id/id/dasbor-siappakai/dokumentasi/auto-backup-google-drive

**Comment by scqolbu24** [comment]
Proses Pengerjaan Issue ini:

- [x] Install rclone
- [x] Konfigurasi rclone ke Google Drive
- [x] Panduan https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-dasbor-siappakai poin 14
- [x] Penyesuaian Backup Database dan Backup Folder Desa -> Kondisi setiap 2 hari sekali dengan cek backup terakhir
- [x] Update `tanggal_akhir_backup` di tabel pelanggan
- [x] Buat Command Auto Backup ke Google Drive setiap 2 hari sekali Jam 4 pagi
      a. Buat folder baru di Google Drive melalui perintah di VPS menggunakan rclone
      b. Unggah backup ke folder baru di Google Drive
- [x] Migrasi Jadwal Tugas

**Comment by habibie11** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/311
