### ISSUE TITLE
Dashboard: Update versi OpenSID Premium

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#3]
Deteksi ada versi premium.
Tutup akses site premium aktif dan tidak aktif.
Lakukan backup database site premium aktif dan tidak aktif secara otomatis.
Geser/rename script versi premium secara otomatis sbb:

1. P -> P-1
2. P-1 -> P-2
3. P-2 -> P-3
4. P-4 -> P-5

Isi P dengan versi premium terbaru.
Sesuaikan symlink semua versi premium yg tidak aktif. Site premium aktif tetap mengarah ke P.

Untuk setiap versi premium, juga ada script untuk:

1. OpenSID API untuk versi premium ybs
2. PBB untuk versi premium ybs

Catatan: pelanggan premium yg sdh tidak aktif lebih dari 5 bulan diganti menjadi pelanggan umum.

**Comment by scqolbu24** [comment]
issue ini dibuka kembali, perlu penyesuaian untuk PBB dan API

**Comment by scqolbu24** [comment]
Issue [Dashboard: Update versi OpenSID Premium #3](https://github.com/OpenSID/wiki-saas/issues/3) ditutup dan dipecah menjadi issue berikut : 
1. [Dashboard : Update PBB #24](https://github.com/OpenSID/wiki-saas/issues/24)
2. [Dashboard : Update API #25](https://github.com/OpenSID/wiki-saas/issues/25)
