### ISSUE TITLE
Symlink master template

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#30]
Dasar [issue #11 Dashboard: API pelanggan SaaS baru](https://github.com/OpenSID/wiki-saas/issues/11)
Saat ini untuk master template yang digunakan berada di luar dasboard saas, sehingga ketika ada perubahan perlu copy folder tersebut manual. Solusinya dibuatkan symlink master template agar setiap perubahan ikut update.  

- [x] Master Template Opensid (mkdir)
- [x] Master Template Pbb (mkdir)
- [x] Master Template API (mkdir)
- [x] Multisite (mkdir)
- [x] Index.php di Opensid (symlink)
- [x] Index.php di Pbb (symlink)
- [x] Index.php di Api (symlink)
- [x] Index.php di Dashboard Saas (symlink)

Tambahan, cek berikut agar dapat berjalan otomatis :
- [x] php artisan key:generate di pbb
- [x] php artisan key:generate di api
- [x] php artisan migrate --seed di pbb
- [x] php artisan migrate --seed di api
- [x] cacert.pem di opensid

**Comment by apidong** [comment]
cacert.pem di opensid ke igonore sama git. mungkin kalau ini harus manual saat configurasi server vps

**Comment by scqolbu24** [comment]
cacert.pem menurut info dari bung akas di generate ketika install opensid

**Comment by scqolbu24** [comment]
setelah dilakukan uji joba sudah berhasil, sehingga issue ini ditutup dan telah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/33
