### ISSUE TITLE
Bug : tidak bisa tambah dan konfigurasi tema

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-siappakai#301]
Berdasarkan laporan dari Pak Ariandi pada discord hari selasa (11/08/2023)
Error berikut hanya terjadi di browser chrome sedangkan di firefox berjalan lancar
ketika di halaman ke 2, 3 dst di halaman pelanggan/desa

- [ ] Tambah Tema Pro
- [ ] Konfigurasi Tema Pro

![image](https://github.com/OpenSID/wiki-saas/assets/56639378/c076cbf6-c96c-41e4-b051-c4f2a6904d3a)

**Comment by vickyrolanda** [comment]
issue ini perlu di analisa lanjutan agar tidak pengerjaan berulang -ulang terkait konfig dimasing -masing tema & jika ada tema baru tidak menjadi issue baru tambahan di SiapPakai.

@habibie11 @scqolbu24

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/434
