### ISSUE TITLE
Tambah dan sesuaikan konfigurasi tema dengan versi terbaru

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-siappakai#306]
Berdasarkan pertemuan dengan pelaksana pada hari Selasa 08 Agustus 2023, terdapat permintaan untuk penambahan dan penyesuaian kolom untuk tema denava dan denatra. ini dilakukan karna tema tersebut ada perubahan konfigurasi di versi yang terbaru.

penyesuaian yang perlu dilakukan adalah :
- [x] tambah kolom chats
- [x] tambah kolom widget
- [x] tambah kolom hide_layanan
- [x] tambah kolom hide banner layanan
- [x] tambah kolom hide banner laporan
- [x] tambah kolom style
- [x] API

repo tema :
- https://github.com/ariandii/denatra
- https://github.com/ariandii/denava

**Comment by scqolbu24** [comment]
Yang perlu dikerjakan ada di Layanan dan SiapPakai danmasing-masing dibuatkan issuenya.

Untuk yang dikerjakan atau disesuaiakan di SiapPakai adalah:

- [x] Buat migrasi untuk penambahan kolom chats, hide_layanan, widget pada table tema_konfigurasi
- [x] Model Tema Konfigurasi

Penyesuaiannya lainnya dapat dilihat di file-file berikut:
![image](https://github.com/OpenSID/wiki-saas/assets/68048807/532ee442-0199-4607-8bd1-8d9ef9f66d86)

**Comment by habibie11** [comment]
setelah diskusi dengan pelaksana, ada update penambahan config baru untuk tema denatra dan denava. penambahan tersebut adalah :
-  style : Tersedia 3 pilihan style, ubah dengan menulis tourism atau gogreen atau classic untuk tema denava
-  hide banner layanan : Sembunyikan Info Jumlah Layanan Surat Pengantar di halaman website
-  hide banner laporan : Sembunyikan Info Perkembangan Penduduk di halaman website

cc Pak @scqolbu24 @vickyrolanda

**Comment by scqolbu24** [comment]
Review: 
- [x] Buat migrasi untuk penambahan kolom chats, hide_layanan, widget pada table tema_konfigurasi
- [x] Model Tema Konfigurasi

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/305
