### ISSUE TITLE
filemanager access denied

### ISSUE THREAD

**Issue by habibie11** [OpenSID/wiki-siappakai#309]
https://trello.com/c/PuGrMZRy/41-filemanager-access-denied

![Image](https://user-images.githubusercontent.com/56639378/267823792-3740239b-6b0c-4b1c-9906-e67ffbc02421.png)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/319
