### ISSUE TITLE
Hapus backup google drive

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#310]
backup dilakukan setiap 2 hari sekali, saat ini kapasitas backup adalah sekitar 3 GB dan kapasitas google drive free adalah 15 GB, sehingga hanya bisa dilakukan 5 kali backup dengan demikian sebelum backuo yang ke 5 harus dihapus terlebih dahulu backup yang paling lama.

Jika sudah berlangganan kapasitas 100 GB maka dapat tersedia setiap kali backup dengan kapasitas 5 GB sebanyak 20 kali backup.

**Comment by habibie11** [comment]
sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/313
