### ISSUE TITLE
penyesuaian konfigurasi email

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#311]
Setelah dilakukan config-email-opensid kemudian jalankan perintah dibawah in terjadi eror, sehingga perlu adanya penyesuaian pada konfigurasi:

- [x] Update domain
- [x] Update pelanggan
- [x] Update Tema Konfigurasi
- [x] Update Token Premium

**Comment by scqolbu24** [comment]
Cara replikasi issue ini,
1. Buka halaman pelanggan
2. Klik Tombol Pengatruan Email OpenSID
3. Inpus konfigurasi email
4. cek file config pada desa maka akan terisi
5. kemudian jalankan perintah-perintah yang sesuai pada deskripsi issue ini maka config email akan kosong
```
// config email
$config['protocol']  = '';  // mail   mail, sendmail, or smtp The mail sending protocol.
$config['smtp_host'] = '';      // SMPT Server Address.
$config['smtp_user'] = '';      // SMPT Username.
$config['smtp_pass'] = '';      // SMPT Password.
$config['smtp_port'] = '';      // SMTP Port.
```

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/321
