### ISSUE TITLE
penyesuaian app_url pada dasbor siappakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#314]
Pada instalasi sesuai dengan panduan https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-dasbor-siappakai
mulai poin 5 yaitu mengisi namadomain, nama domian tersebut digunakan untuk mengubah pada konfigurasi di .env sehingga ketika di GET adalah nama domain pada dasbor siappakai bukan `localhost`. nama domain tersebut digunakan untuk auto backup ke google drive, karena ada kemungkinan auto backup dalam 1 akun ggogle dapat digunakan untuk beberpa server.

Sebenarnya untuk mudahnya dapat diubah langsung melalui .env, namun pertimbangannya adalah proses instalasi pada dasbor siappakai tidak ubah langsung di file .env melainkan melalui perintah-perintah sesuai pada https://panduan.opendesa.id/dasbor-siappakai/dokumentasi#mengenal-perintah-dasbor-siappakai

Adapun yang perlu disesuaikan pada perubahan ini adalah:

- [x] tambahkan app_url pada master-template/env.example
- [x] tambahkan app_url pada Https/Controller/Helpers/EnvController
- [x] tambahkan setAppUrl dan getAppUrl pada Https/Controller/Helpers/AttributeSiapPakaiController
- [x] Install Saas
- [x] ConfigTokenGithub
- [x] ConfigFtp
- [x] ConfigApp
- [x] ConfigOpenKab

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/320
