### ISSUE TITLE
Sesuaiakan host untuk backup google drive

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#317]
host belum diarahkan sesuai dengan server masing-masing, namun menggunakan default waktu testing.

sesuaikan juga waktu backup 2 hari sekali hanya berlaku ketika google drive diaktifkan.

**Comment by scqolbu24** [comment]
host belum diarahkan sesuai dengan server masing-masing, namun menggunakan default waktu testing.

sesuaikan juga waktu backup 2 hari sekali hanya berlaku ketika google drive diaktifkan.

**Comment by habibie11** [comment]
Sudah dikerjakan di PR https://github.com/OpenSID/dashboard-saas/pull/326
