### ISSUE TITLE
Penyesuaian tombol unduh database dan folder desa di halaman pelanggan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#319]
Dengan adanya issue https://github.com/OpenSID/dashboard-saas/issues/317 maka perlu ada penyesuaian untuk tombol unduh database dan folder desa pada halaman pelanggan di kolom aksi.

![Image](https://github.com/OpenSID/wiki-saas/assets/68048807/174ae34e-2e58-47db-a3c1-ba0097feb098)

issue tambahan: Seharusnya jika tidak ada folder desa maka tombol non aktif / disabled

**Comment by habibie11** [comment]
sudah diselesaikan melalui PR https://github.com/OpenSID/dashboard-saas/pull/333
