### ISSUE TITLE
Tambahkan queue monitoring

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-siappakai#33]
tambahkan modul untuk monitoring queue yang gagal.

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/177142771-72ed96fa-e87e-4184-8cec-3e58a34fb2ea.png)
tangkapan layar

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/29
