### ISSUE TITLE
Bug: SiapPakai3 penyesuaian permission ubah www-data menjadi www

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#333]
Pada devsaas, siappakai2 dan pada server kota bima menggunakan permission `www-data` namun untuk siappakai3 permisiion menggunakan `www`, dengan demikian perlu dibuatkan pengaturan aplikasi untuk penggunaan permission, dan ubah perintah pada script sesuai dengan pengaturan tersebut.

**Comment by scqolbu24** [comment]
sudah dkerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/354
