### ISSUE TITLE
Bug: SiapPakai3 belum dapat upload file manager

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#335]
![image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/cfc374cd-e329-4581-94e6-a398dd23f376)

**Comment by scqolbu24** [comment]
dikarenakan asset menggunakan symlink

**Comment by pandigresik** [comment]
Perbaikan pada OpenSID https://github.com/OpenSID/premium/pull/3808

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/premium/pull/3810

**Comment by scqolbu24** [comment]
Telah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/440
