### ISSUE TITLE
Bug: SiapPakai3 belum dapat menjalankan multiphp untuk API dan OpenSID

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#336]
file .htaccess pada master-template di 3 aplikasi dan di siappakai itu sendiri:
1. template-desa/.htaccess
2. template-api/.htaccess
3. template-pbb/.htaccess
4. public/.htacess (siappakai)
dari file tersebut terdapat kondisi untuk mengecek file php tertentu yang digunakan, misalkan PHP 7.4, PHP 8.1

saat ini semua aplikasi sudah suport menggunakan PHP 8.1, namun tidak menutup kemungkinan akan terjadi hal yang sama pada versi seblum 2401.0.0 yaitu terdapat perbedaan versi php, sehingga diperlukan pengaturan menggunakan MultiPHP. 

Refrensi:
1. https://stackoverflow.com/questions/22026144/if-else-statement-in-htaccess
2. https://stackoverflow.com/questions/13992212/htaccess-if-statement

cek pada .env menggunakan `MULTIPHP=true`

<If "%{env} == 'foo'">
    # configuration for foo
</If>
<Else>
    # default configuration
</Else>

**Comment by scqolbu24** [comment]
sebelum mengerjakan issue ini, maka kerjakan issue https://github.com/OpenSID/wiki-saas/issues/344 terlebih dahulu.

**Comment by scqolbu24** [comment]
cek issue [Install / update API](https://github.com/OpenSID/wiki-saas/issues/342) untuk multi php atau tidak

**Comment by scqolbu24** [comment]
solusi untuk issue ini bisa menerapkan seperti ini:

- [x] buat .htaccess dengan kondisi sudah ada cek kondisi php yang disimpan di master-template
- [x] hapus baris 28 sampai 32 di .httacess pada dashboard-saas/public/.htaccess
- [x] Buat kondisi ketika update saas untuk pengecekan multiphp dan sesuaikan .htaccess yang digunakan

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/371
