### ISSUE TITLE
Ketika install tema dari layanan terdapat perubahan yang perlu di commit, seharusnya tidak perlu adanya commit

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#338]
![Image](https://github.com/OpenSID/wiki-saas/assets/68048807/b6885378-653c-42d3-adbe-97e7e4bcbdfd)

**Comment by scqolbu24** [comment]
issue ini ditutup, karena sudah beberapa kali dilakukan aman.
