### ISSUE TITLE
error SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-siappakai#34]
`
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-07-05 02:40:44 --> Severity: error --> Exception: SQLSTATE[HY000] [2002] No such file or directory (SQL: 
        CREATE TABLE `user` (
          `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
          `username` varchar(100) DEFAULT NULL,
          `password` varchar(100) NOT NULL,
          `id_grup` int(5) NOT NULL,
          `email` varchar(100) DEFAULT NULL,
          `last_login` datetime DEFAULT NULL,
          `email_verified_at` datetime DEFAULT NULL,
          `active` tinyint(1) unsigned DEFAULT 0,
          `nama` varchar(50) DEFAULT NULL,
          `company` varchar(100) DEFAULT NULL,
          `phone` varchar(20) DEFAULT NULL,
          `foto` varchar(100) DEFAULT 'kuser.png',
          `session` varchar(40) NOT NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `username` (`username`),
          UNIQUE KEY `email` (`email`)
        );
      ) /var/www/html/master-opensid/premium/vendor/illuminate/database/Connection.php 712

`

**Comment by apidong** [comment]
@agungsugiarto

**Comment by scqolbu24** [comment]
koneksi localhost diganti 127.0.0.1
