### ISSUE TITLE
Penyesuaian pengaturan ftp pada aaPanel

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#341]
Perbedaan VPS biasa dan aaApnel:
1. VPS biasa
    a. pengaturannya pada FTP di file .env API `<path>/multisite/kode_desa` 
    b. 1 akun FTP digunakan untuk semua pelanggan dan akun tersebut dikonfigurasikan di .env pada dasbor siappakai
2. VPS aaPanel
    a. pengaturannya pada FTP di file .env API `/`
    b. 1 akun FTp digunakan 1 desa untuk keamanan

Dari issue tersebut, maka perlu dibuatkan aotomasi:
1. Install FTP ketika mendaftarkan pelanggan melalui layanan yaitu pada perintah newsite (API), perubahan filenya ada di BuildSite.
2.Buat konfigurasi pada file BuildSite untuk penyesuaian pengaturan user dan password FTP.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/437
