### ISSUE TITLE
Penerapan Tema Palanta

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#347]
Sebagai Fasilitas SiapPakai maka disediakan tema gratis palanta yang dapat di pilih di pengaturan tema, maka dari perlu diterapkan dengan langkah berikut:

- [x] Buat perintah console untuk install Tema Bawaan simpan pada directory `master-tema-gratis`
- [x] Buat perintah untuk update ketika ada perubahan pada repo tema
- [x] Buat perintah cronjob untuk proses install pertama kali dan update tema
- [x] Buat symlink tema ketika install master tema opensid
- [x] Buat symlink tema ketika update opensid

**Comment by scqolbu24** [comment]
- [x] Menambahkan kolom jenis tema pada pengaturan tema
- [x] Membuat seeder pengaturan tema 
- [x] Mengubah menu tema pro menjadi tema
- [x] Menambahkan jenis tema pada form tema
- [x] Buat perintah console untuk install Tema Bawaan simpan pada directory `master-tema-gratis`
- [x] Buat perintah untuk update ketika ada perubahan pada repo tema
- [x] Buat perintah cronjob untuk proses install pertama kali dan update tema
- [x] Buat symlink tema ketika install master tema opensid ke folder vendor/themes
- [x] Buat symlink tema ketika update opensid ke folder vendor/themes
- [x] Buat Job Instal Tema ke vendor/themes 
- [x] Ketika Klik Simpan Pengaturan Tema Instal Master Tema Gratis

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/401
