### ISSUE TITLE
Bug: Internal Server Eror

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#357]
![Image](https://github.com/OpenSID/wiki-saas/assets/68048807/837d89d6-d2fe-4620-b987-74ebc675ef9b)

solusinya adalah perbaiki pada .htaccess, bisa dilakukan pada opensid atau buat file sendiri di siappakai

**Comment by habibie11** [comment]
![image](https://github.com/OpenSID/wiki-saas/assets/56639378/5116f489-ad64-4b3b-b0e3-2e8f5503a59b)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/375
