### ISSUE TITLE
Sesuaikan pengaturan install modul pada SiapPakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#358]
Perdasarkan diskusi terakhir bahwa perlu ada penambahan pengaturan untuk tombol pasang modul pada siappakai. 

- [ ] Tambahkan tombol pasang / install modul
- [ ] Sesuaikan seperti pengaturan tema pada siappakai

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/377
