### ISSUE TITLE
Symlink domain pbb dan api di masing-masing desa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#36]
Symlink domian pbb dan api untuk masing masing-masing desa, misalnya:

- [x] desacontoh.opendesa.id/pbb
- [x] desacontoh.opendesa.id/api

**Comment by scqolbu24** [comment]
Symlink domian pbb dan api untuk masing masing-masing desa, misalnya:

- [ ] desacontoh.opendesa.id/pbb
- [ ] desacontoh.opendesa.id/api

**Comment by apidong** [comment]
sudah diperbaiki di https://github.com/OpenSID/dashboard-saas/pull/32
