### ISSUE TITLE
Penerapan Docker pada server SiapPakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#360]
Mempersiapkan server SiapPakai dan Dasbor SiapPakai

- [ ] Install Server VPS berupa LAMP
- [ ] Install ionCube
- [ ] Install SSL
- [ ] Install Unzip
- [ ] Install Composer
- [ ] Install Git
- [ ] Instal FTP
- [ ] Install file2ban
- [ ] Install Dasbor SiapPakai

**Comment by emhandho** [comment]
Progres Penerapan Docker pada server Siappakai

- [x]  masih mengalami error pada extention php, sehingga berimbas pada pemasangan ionCube
- [x] Install ionCube
- [x] Install SSL
- [x] Install Unzip
- [x] Install Composer
- [x] Install Git
- [x] Instal FTP
- [x] Install file2ban
- [ ] Install Dasbor SiapPakai

**Comment by emhandho** [comment]
Progres Penerapan Docker pada aplikasi Siappakai
Untuk proses instalasi semua third party sudah berjalan dengan baik, masih ada error yang ditemui pada saat proses instalasi Dasbor SiapPakai, yaitu pada proses yang terakhir.
Diantara error yang masih ditemui:
- Koneksi ke Database masih belum berjalan dengan baik
- Masih menemui error ketika menjalankan perintah ```php artisan ...``` didalam kontainer docker

**Comment by emhandho** [comment]
Progres Penerapan Docker pada aplikasi Siappakai tanggal 05 Maret 2024
Untuk proses instalasi semua third party sudah berjalan dengan baik, masih ada error yang ditemui pada saat proses instalasi Dasbor SiapPakai, yaitu pada proses yang terakhir.
Diantara error yang masih ditemui:
- Koneksi ke Database masih belum berjalan dengan baik
- Masih mengalami error pada extention php, sehingga berimbas pada pemasangan ionCube

**Comment by emhandho** [comment]
Progres Penerapan Docker pada aplikasi Siappakai tanggal 06 Maret 2024
Untuk proses instalasi semua third party sudah berjalan dengan baik.
Langkah yang masih terkendala pada saat langkah install Dasbor SiapPakai:
- Masih menemui error ketika menjalankan perintah php artisan ... didalam kontainer docker, utamanya pada saat set ConfigEnv, .env.example tidak berubah sesuai dengan yang diinginkan

**Comment by emhandho** [comment]
Progres Penerapan Docker pada aplikasi Siappakai tanggal 07 Maret 2024
Untuk proses instalasi semua third party sudah berjalan dengan baik.
Langkah yang masih terkendala pada saat langkah install Dasbor SiapPakai:
- Masih menemui error ketika menjalankan perintah php artisan ... didalam kontainer docker, utamanya pada saat set ConfigEnv, .env.example tidak berubah sesuai dengan yang diinginkan

Rencana hari ini tanggal 07 Maret 2024:
Mencoba diimplementasikan ke server vps [admin@103.54.170.135](https://admin@103.54.170.135/)



![Image](https://github.com/OpenSID/wiki-siappakai/assets/34464673/0d2eba7b-5158-46f3-9304-45ce824a69c8)

**Comment by emhandho** [comment]
Progres Penerapan Docker pada aplikasi SiapPakai tanggal 13 Maret 2024
Untuk proses instalasi semua third party sudah berjalan dengan baik.
Langkah yang masih terkendala pada saat langkah install Dasbor SiapPakai:
- Menemui kendala tidak bisa menjalankan Supervisor secara otomatis didalam docker container
- Menemui error ketika menjalankan perintah php artisan siappakai:install-master, error seperti gambar dibawah:


![Image](https://github.com/OpenSID/wiki-siappakai/assets/34464673/5a218d08-8b9e-432c-aea6-14a18908a92a)

**Comment by scqolbu24** [comment]
> Progres Penerapan Docker pada aplikasi Siappakai tanggal 07 Maret 2024 Untuk proses instalasi semua third party sudah berjalan dengan baik. Langkah yang masih terkendala pada saat langkah install Dasbor SiapPakai:
> 
> * Masih menemui error ketika menjalankan perintah php artisan ... didalam kontainer docker, utamanya pada saat set ConfigEnv, .env.example tidak berubah sesuai dengan yang diinginkan
> 
> Rencana hari ini tanggal 07 Maret 2024: Mencoba diimplementasikan ke server vps [admin@103.54.170.135](https://admin@103.54.170.135/)
> 
> ![Image](https://private-user-images.githubusercontent.com/34464673/310734510-0d2eba7b-5158-46f3-9304-45ce824a69c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjA5ODMsIm5iZiI6MTcxMDMyMDY4MywicGF0aCI6Ii8zNDQ2NDY3My8zMTA3MzQ1MTAtMGQyZWJhN2ItNTE1OC00NmYzLTkzMDQtNDVjZTgyNGE2OWM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZTI5ZDZkOTczY2E0NTc0NzEwN2ZiZDhkNjNiMzlhNzMxMWNjMDRjZDE1MmRlOWNkMzBlMzEwMjZjYjJlMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oEMC_uzKz8OE33qMQqwuNA4gQKKFYMSrWd55dYEPLsc)

sudah dikerjakan pada PR https://github.com/OpenSID/dashboard-saas/pull/390, bisa gunakan branch tersebut

**Comment by scqolbu24** [comment]
mas @emhandho mohon dibuatkan PR file docker'nya

**Comment by scqolbu24** [comment]
> Progres Penerapan Docker pada aplikasi SiapPakai tanggal 13 Maret 2024 Untuk proses instalasi semua third party sudah berjalan dengan baik. Langkah yang masih terkendala pada saat langkah install Dasbor SiapPakai:
> 
> * Menemui kendala tidak bisa menjalankan Supervisor secara otomatis didalam docker container
> * Menemui error ketika menjalankan perintah php artisan siappakai:install-master, error seperti gambar dibawah:
> 
> ![Image](https://private-user-images.githubusercontent.com/34464673/312387062-5a218d08-8b9e-432c-aea6-14a18908a92a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODA4OTAsIm5iZiI6MTcxMDM4MDU5MCwicGF0aCI6Ii8zNDQ2NDY3My8zMTIzODcwNjItNWEyMThkMDgtOGI5ZS00MzJjLWFlYTYtMTRhMTg5MDhhOTJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAxNDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MzIwNDMyNTgxNTViZjIyYjgwMGFmMTMxOGVjZDBlYzRmNzdiMzY4ZDAwOGM0ZjVlNGE5ZWM4NzdjYjAwNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xl_TOvh2BNT7BT5e7WZc73ypHx1fj5GXsX9m3IlVSVI)

Ditelusuri dari mulai baris 135, kemungkinan karena permission

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/docker-manifest/pull/1
