### ISSUE TITLE
Bug: API selalu eror ketika jalankan cronjob

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#363]
dikarenakan tidak ada folder vendor

![Image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/b29b3b52-55cb-4097-a87e-80bfe54f6bd5)

**Comment by scqolbu24** [comment]
![api bug](https://github.com/OpenSID/wiki-siappakai/assets/68048807/33957517-8d7b-460d-a51c-e9e2f57fe2dd)

**Comment by scqolbu24** [comment]
cek manual : 
<img width="650" alt="cek manaul" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/64adbb0b-8718-459d-8ff5-53a91aa0a42c">

terkait permission menggunakan root, setelah diubah permissionnya erornya berikut.
<img width="660" alt="image" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/45f853fe-8ffa-4b49-baaa-7427311b2a13">

dikarenakan belum ada file .env
<img width="439" alt="version" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/f2efe22d-cf2b-40a6-b00d-530511bb639b">

**Comment by scqolbu24** [comment]
untuk kondisi multiphp dan symlink perbaikan pada PR https://github.com/OpenSID/dashboard-saas/pull/388

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/388
