### ISSUE TITLE
Penyesuaian Install Master di aaPanel

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#366]
Dengan adanya penyesuaian di aaPanel untuk penggunaan Multiphp atau tidak maka pada proses install master perlu disesuaikan yaitu:

Pada File Install master tambahkan perintah untuk kondisi menghapus/tidak .htaccess yang ada di masing-masing aplikasi:
1. OpenSID: <master-opensid>/premium/.httaccess
2. PBB: <master-pbb>/pbb_desa/public/.htaccess
3. API: <master-api>/openisd-api/public/.htaccess

jika pengaturan menggunakan multiphp maka dihapus dan dibuatkan symlink dari master-template/<masing-masing-aplikasi>

jika pengaturan tidak menggunakan multiphp maka hanya copy dan rename htaccess.txt

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dasbor-siappakai/pull/535
