### ISSUE TITLE
Update token ketika perpanjangan Saas atau Langganan Premium

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#37]
pada saat adanya perpanjangan langganan, baik premium ataupun saas maka token akan berubah sehingga perlu diubah juga aplikasi yang berkaitan yaitu:
- [x] config.php untuk OpenSID
- [x] .env untuk PBB
- [x] .env untuk API

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/35
