### ISSUE TITLE
BUG: Install Saas

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#370]
terjadi eror pada saat menjalankan perintah `php artisan siappakai:install-saas`
<img width="643" alt="isntall saas" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/eebaa174-308a-4a24-a95c-9c31ac318c83">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/390
