### ISSUE TITLE
Bug: Konfigurasi Token Github

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#371]
Ketika menjalankan perintah untuk konfigurasi token github yaitu php artisan siappakai:install-master --kode_desa=isikodedesa --token_premium=isitokenpremium terjadi eror berikut:

![Image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/c03e8944-6271-442f-926d-275d0c7ba64d)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/391
