### ISSUE TITLE
Bug: Proses Instalasi Master Tidak dapat konfigurasi env PBB dan API

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#372]
Pada saat melakukan proses menjalankan `php artisan siappakai:install-master --kode_desa=isikodedesa --token_premium=isitokenpremium`, tidak dapat konfigurasi .env yang ada di PBB dan API sehingga pada PBB tidak dapat melakukan migrasi database.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/393
