### ISSUE TITLE
bug install desa ke 2 berdasarkan laporan dan implementasi di tabanan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#378]
![image](https://github.com/OpenSID/wiki-siappakai/assets/59082428/b2d7528e-b8d9-4732-942e-7a912633aa41)

berdasrkan diskusi bahwa penjelasan issue ini sudah dilakukan berdasarkan pertemuan langsung di discord dan sudah di jelaskan kepada mas afandi.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/403
