### ISSUE TITLE
Bug: Perbaiki status langganan opensid

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#384]
Pada saat pertama kali mendaftarkan desa yang tidak menggunakan token pada status langganan terisi `umum` pada `langganan opensid`, kemudian di hari berikutnya status langganan tersebut menjadi kosong atau terhapus karena ada cronjob yang dijalankan. seharusnya tetap terisi `umum`. 

![image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/a22a5ef1-13bd-4ae6-a05c-d9fcd5ce603b)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/408
