### ISSUE TITLE
Icon Informasi wilayah, penduduk, keluarga, dst pada Halaman Beranda tidak tampil

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-siappakai#386]
Jelaskan error yg dialami

Icon Informasi wilayah, penduduk, keluarga, dst pada Halaman Beranda tidak tampil di aplikasi opensid premium pengguna layanan siapPakai

Cara untuk mereplikasi errornya
1. login ke opensid
2. lihat halaman beranda 

Hasil yg diharapkan
Icon tampil 

Tangkapan layar dan log error

![image](https://github.com/OpenSID/wiki-siappakai/assets/55429781/f464c924-69c5-4a5d-88ca-71e08d3a191d)

Rilis Versi OpenSID
Rilis Premium

Versi OpenSID
2404.0.1

**Comment by scqolbu24** [comment]
setelah dicek di beberapa pelanggan siappakai, tidak semua desa mengalami hal tersebut
<img width="952" alt="image" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/9651a51a-0a25-4ef4-b76f-d70d020ebb57">

<img width="953" alt="image" src="https://github.com/OpenSID/wiki-siappakai/assets/68048807/b9ac7c9f-ff43-44f3-8316-227adbbc23e0">

**Comment by pandigresik** [comment]
ada contoh desa yang mengalami hal tersebut  ? 
bisa diberikan akses ?

**Comment by scqolbu24** [comment]
untuk pengguna lama, dikarenakan asset masih menggunakan versi lama yaitu copy paste bukan menggunakan symlink

**Comment by pandigresik** [comment]
tidak ada perbaikan, dikarenakan siappakai akan menggunakan metode copy folder assets tidak lagi menggunakan symlink, ini juga akan menyelesaikan masalah responsive file manager pada issue https://github.com/OpenSID/wiki-siappakai/issues/335

**Comment by scqolbu24** [comment]
telah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/440
