### ISSUE TITLE
Link storage pada aplikasi pbb

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#39]
Pada pengaturan -> Aplikasi ketika upload gambar status pesannya berhasil namun tidak dapat menampilkan gambar yang dirubah (masih tetap).

**Comment by apidong** [comment]
sudah diperbaiki melalui eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZGV2bGF5YW5hbi5vcGVuZGVzYS5pZCIsImlhdCI6MTY1NzU0ODE2NSwiZXhwIjoxODM5MjQ3MzY1LCJuYmYiOjE2NTc1NDgxNjUsImp0aSI6IjRiNGI4NzYxNTMwYjZkOGQ4YjMyMTg0MWUyYmM5NmJjN2Y4MTk1NjY3Y2E0ZGY0MjNlZTY0N2IyNjExYTA2MjQiLCJzdWIiOiIxNDE5IiwicHJ2IjoiZjkzMDdlYjVmMjljNzJhOTBkYmFhZWYwZTI2ZjAyNjJlZGU4NmY1NSIsImRlc2FfaWQiOiIxNy4wMS4wMy4yMDIyIiwiZG9tYWluIjoiaHR0cHM6XC9cL3hlbm8ucHJpbWFzb2Z0LmNvaWQiLCJ0YW5nZ2FsX2JlcmxhbmdnYW5hbiI6eyJtdWxhaSI6IjIwMjItMDQtMTYiLCJha2hpciI6IjIwMjUtMDctMTAifX0.UdlcwpytNJHifBF27G3HbPEd_r0aaCFupQn7LqV5zmE
