### ISSUE TITLE
Ketika Update perlu penyesuaian pada folder modul

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#390]
- [x] Hapus folder Modules pada premium setelah clone versi terbaru
- [x] Salin folder Modules dari premium_1 ke premium jika rilis bulanan
- [x] Salin folder Modules dari premium_rev01 ke premium jika rilis mingguan atau rev

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/419
