### ISSUE TITLE
Bug: Akses Menu Modul eror ketika database masih kosong

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#399]
Akses Menu Modul Eror ketika database masih kosong atau seeder awal

![Image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/5ddb30bf-5e9a-4c01-aa6c-525afeeed490)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/432
