### ISSUE TITLE
Library/plugin Livewire dan Fortawesome pada aplikasi pbb belum berfungsi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#40]
Pada saat menambahkan data sppt, pilihan rayon, rt, objek pajak dan subjek pajak belum dapat berfungsi karena komponen livewire belum di load. Ketika pada url ditambahkan pbb di depan livewire (pbb/livewire), maka livewire bisa di load.

selain itu fortawesome juga belum dapat di load.

kedua issue tersebut diatas disebabkan karena aplikasi pbb bukan diinstall pada domain sendiri (misalkan http://desacontoh.opendesa.id/pbb)

<img width="100%" alt="livewire" src="https://user-images.githubusercontent.com/68048807/178707027-99aaff5d-0d69-4757-b835-5f7566fbf661.PNG">

**Comment by scqolbu24** [comment]
solusi untuk livewire :
1. menambahkan vendor livewire dengan jalankan perintah php artisan livewire:publish --assets
2. menambahkan livewire.php di config dengan jalankan perintah php artisan vendor:publish --tag=livewire:config
3. ubah pada baris ke 57 script berikut 'asset_url' => env('ASSET_URL', null),
4. ubah pada baris ke 71 script berikut 'app_url' => env('APP_URL', 'http://localhost'),
5. tambahkan pada .env script berikut ASSET_URL=nama-domain/pbb

sebaiknya perubahannya langsung pada repo pbb sehingga berfungsi pada rilis-rilis berikutnya bukan hanya di saas

**Comment by scqolbu24** [comment]
solusi untuk font awesome:
buat symlink folder fonts yang ada di public sejajar dengan folder pbb

**Comment by vickyrolanda** [comment]
Untuk PBB sudah di terapkan di https://github.com/OpenSID/pbb_desa/pull/108

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/51
