### ISSUE TITLE
Bug: Jalankan Reload Apache

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#402]
Issue ini terjadi hanya diserver kota bima yaitu ketika melakukan perubahan pada script harus menjalankan perintah : 
sudo service apache2 reload

**Comment by pandigresik** [comment]
cara replikasinya bagaimana ? ini tidak berkaitan langsung dengan aplikasi siappakai, lebih ke konfigurasi server masing-masing

**Comment by pandigresik** [comment]
This is a common behavior in Apache2. By default, Apache2 doesn't automatically reload the configuration files or restart the server when you make changes to your application code.

Here are a few reasons why this happens:

Apache2's default behavior: Apache2 is designed to serve static content efficiently. It caches the content in memory to improve performance. When you make changes to your code, Apache2 doesn't automatically detect the changes and reload the configuration.
Config file parsing: Apache2 parses the configuration files (e.g., apache2.conf, sites-available/, sites-enabled/) only when it starts or reloads. If you make changes to the configuration files, Apache2 won't detect the changes until you reload or restart the service.
To overcome this issue, you have a few options:

1. Enable Apache2's EnableSendfile directive:

In your Apache2 configuration file (e.g., apache2.conf or a virtual host file), add the following directive:

bash

Open In Editor
Edit
Run
Copy code
EnableSendfile Off
This will disable the caching of static content, allowing Apache2 to serve the latest version of your application code.

2. Use mod_watch:

mod_watch is an Apache2 module that allows you to monitor changes to files and directories. You can configure it to reload Apache2 when changes are detected.

To enable mod_watch, add the following lines to your Apache2 configuration file:

bash

Open In Editor
Edit
Run
Copy code
LoadModule watch_module /usr/lib/apache2/modules/mod_watch.so
Watch *.php *.html *.css *.js
This will monitor changes to PHP, HTML, CSS, and JavaScript files. When a change is detected, Apache2 will reload the configuration.

3. Use a script to automate the reload:

Create a script that runs systemctl reload apache2 whenever you make changes to your application code. You can use a tool like inotifywait to monitor changes to your code directory and trigger the reload.

For example, create a script reload_apache.sh with the following content:

bash

Open In Editor
Edit
Run
Copy code
#!/bin/bash

inotifywait -q -e modify,create,delete /path/to/your/code/directory
systemctl reload apache2
Make the script executable with chmod +x reload_apache.sh and run it in the background with ./reload_apache.sh &.

4. Use a development environment with automatic reloading:

Consider using a development environment like docker-compose or vagrant that can automatically reload Apache2 when changes are detected.

Remember to adjust the configuration according to your specific needs and environment.

**Comment by eddieridwan** [comment]
@scqolbu24 di info bung @pandigresik terlihat bahwa jika menggunakan docker-compose Apache akan di-reload secara otomatis.

Kita perlu mengusahakan menerapkan docker-compose tersebut.

**Comment by scqolbu24** [comment]
> This will disable the caching of static content, allowing Apache2 to serve the latest version of your application code.

sudah mencoba cara :
1.  masih belum bisa
<Directory "/path-to-nfs-files">
  EnableSendfile Off
</Directory>

2. Watch *.php *.html *.css *.js di /usr/lib/apache2/modules/mod_watch.so masih belum bisa
3. sudah membuat file  reload_apache.sh masih belum bisa

**Comment by scqolbu24** [comment]
Solusinya membuat script : `sudo service apache2 reload` yang dipanggil setelah update SiapPakai, OpenSID, PBB, API atau di cronjob pada perintah terakhir di jadwal tugas.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/451
