### ISSUE TITLE
Set Directory aaPanel

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#403]
Langkah Pengerjaan dan Replikasi di aaPanel: 
1. login ke aaPanel
2. Klik Menu Website
3. Pilih Salah Satu domain yang telah dibuat
4. Klik Menu Site directory
5. Hilangkan Ceklist Anti-XSS attack

![image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/2b91658e-d4a4-4780-a3c8-62eec62ea0a2)

**Pengerjaan yang dilakukan di dalam script yaitu ketika Buildsite / daftarkan pelanggan baru melalui layanan setelah berhasil daftarkan website di aapanel maka hilangkan Ceklist Anti-XSS** 

Jika Anti-XSS attack diperlukan maka cari solusi agar web dapat diakses : 

![Image](https://github.com/OpenSID/wiki-siappakai/assets/68048807/454986e9-e30c-4d5d-bae3-3bd9757bacd1)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/446
