### ISSUE TITLE
Menyediakan untuk mendukung tema ubahan di siappakai

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-siappakai#407]

**Comment by pandigresik** [comment]
bisa dijelaskan lebih detail maksud dari issue ini ?
Apakah maksudnya fitur untuk upload tema ?

**Comment by eddieridwan** [comment]
@vickyrolanda @scqolbu24 mohon tidak lupa, ya, bahwa tema ubahan itu per desa, tidak global untuk semua desa. Dan perlu ada pertimbangan keamanan.

**Comment by pandigresik** [comment]
sepertinya lebih masuk akal jika solusinya melalui upload tema ubahan di opensid karena spesifik per desa. Jika dilakukan di siappakai maka akan cukup merepotkan petugas siappakai untuk upload permintaan tema ubahan pada masing - masing desa

**Comment by eddieridwan** [comment]
Tantangan kebutuhan ini adalah skema untuk verifikasi keamanan dan keabsahan tema yg diunggah. Karena kalau ada malware, resiko pada semua desa, tidak satu saja.

Opsi:

1. otomatis
2. ada proses pemeriksaan manual; atau
3. kombinasi 1 & 2. 

Mungkin yg 3. Lakukan yg dapat dilakukan secara otomatis. Tetapi tetap ada sepasang mata yg memastikan sudah ok.

**Comment by pandigresik** [comment]
Perbaikan pada OpenSID
https://github.com/OpenSID/premium/pull/3824

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/443
