### ISSUE TITLE
Membuat file .htaccess di aplikasi pbb dan api

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#41]
Jika menggunakan Saas maka pelanggan saas cukup menggunakan 1 domain yang mana bisa digunakan untuk opensid, opensid api dan aplikasi pbb. 

OpenSID API diakses dengan menambahkan /api dibelakang nama domain desa
Aplikasi PBB diakses dengan menambahkan /pbb di belakang domain desa

sebagai keamanan source code api dan pbb, maka diperlukan tambahkan file .htaccess di masing-masing apliasi tersebut.
- [x] OpenSID API
- [x] Aplikasi PBB

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/37
