### ISSUE TITLE
Fitur: Ceklist / Multiselect backup google drive dan VPS

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#415]
1. Pada pengaturan aplikasi, terdapat pengaturan cloud storage yaitu memilih google drive atau ke VPS, saat hanya dapat memilih salah satu, kemudian pada issue ini agar dapat memilih keduanya, dapat menggunakan ceklist atau multiple select. 

2. Terdapat perubahan kondisi di perintah google drive dan VPS
3. optionsClouds

**Comment by anangnovriadi** [comment]
PR: https://github.com/OpenSID/dashboard-saas/pull/473
Pict:
![Image](https://github.com/user-attachments/assets/5550d783-8100-4a0e-a267-d9085c19f69a)

cc: @scqolbu24

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/473
