### ISSUE TITLE
penyesuaian repo dashboard saas menjadi dasbor siappakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#417]
untuk issue yang berkaitan penulisan terlebih dahulu, untuk yang menyangkut database di tahap selanjutnya.

contoh issue ini diantaranya:

- [x] perubahan /var/www/html/dashboard-saas diubah menjadi /var/www/html/dasbor-siappakai
- [x] $this->att->getRootFolder() . 'dashboard-saas' diubah menjadi $this->att->getRootFolder() . 'dasbor-siappakai'
- [x] dapat dicari seperti contoh. 

catatan : setelah issue ini digabungkan dan dirilis perlu penyesuaian di server kominfo yang sudah terinstall.

**Comment by apidong** [comment]
> * dasbor-siappakai

sekalian, saya refaktor struktur kode siap pakai ya mas

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/476
