### ISSUE TITLE
Penggantian Nama Domain

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#42]
Ada kemungkinan pelanggan akan mengubah nama domain, sehingga pada layanan dan saas juga diperlukan perubahan menyesuaiakan nama domain yang baru, yang perlu dikerjakan dalam Penggantian nama domain adalah:

- [x] Perubahan nama domain di Layanan
- [x] Membuat API perubahan nama domain
- [x] Penghapusan Domain lama dan pembuatan domain baru di Saas
- [x] Penghapus vhost lama dan pembuatan vhost baru
- [x] Penghapusan SSL lama dan pembuatan SSL baru

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/wiki-saas/issues/42
