### ISSUE TITLE
Bug : logo favicon tidak sama dengan logo desa

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-siappakai#422]
1. logo favicon tidak sama dengan logo desa

![image](https://github.com/user-attachments/assets/1ae96b3d-eb1f-49e7-ab4f-21c4d7327ab2)

**Comment by rgrahardi** [comment]
Logo berubah 
![image](https://github.com/user-attachments/assets/eb4540a9-1247-49fe-8cb6-f5c6cfb2d049)

**Comment by scqolbu24** [comment]
saat ini favicon merupakan symlink yang diambil dari master-opensid/premium/favicon, 
pada rilis opensid versi 2411.0.0 ada penyesuaian favicon sehingga pada siappakai juga perlu disesuaikan symlinknya yaitu ambil dari multisite/....kode.../desa/favicon


catatan: file yang diubah di master-template/template/opensid/index.php pada bagian symlink favicon

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dasbor-siappakai/pull/558
