### ISSUE TITLE
BUG : Tidak bisa Akses Menu Database

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-siappakai#426]
Desa Angseri Database Kab Tabanan tidak bisa akses menu Database

![image](https://github.com/user-attachments/assets/90ea1903-23ce-45a4-9cb9-c6cfa90677d9)

**Comment by eddieridwan** [comment]
@rgrahardi @scqolbu24 sebaiknya masalah seperti ini ditangani awalnya melalui Help Desk. Dan hanya buat issue setelah diketahui persisnya apa yg perlu diperbaiki.

**Comment by scqolbu24** [comment]
issue ini disebabkan karena tidak terdapat symlink pada favicon.ico

favicon.ico diambil dari symlink /multisite/kodedesa/desa/logo/favicon.ico

solusinya adalah :
1. Lakukan pengecekan /multisite/kodedesa/desa/logo/favicon.ico, 
2. Jika tidak ada file favicon.ico pada poin 1, maka salin dari /master-template/template-opensid/desa/logo/favicon.ico ke /multisite/kodedesa/desa/logo/favicon.ico
3. Hilangkan jika ada symlink di multisite/kodedesa/desa/favicon.ico

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dasbor-siappakai/pull/568
