### ISSUE TITLE
Instalasi OpenSID, API, dan PBB menggunakan script

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#43]
Berdasarkan Demo devsaas.opendesa.id padatanggal 14 Juli 2022, maka ada beberapa review yang masih perlu diperbaiki, salah satunya adalah agar dapat mempermudah proses instalasi pertama pada VPS sebagai infrastruktur Dashboard Saas di setiap VPS.

Untuk mendukung hal tersebut dibuatkan script yang nantinya dapat digunakan untuk menginstall OpenSID Premium, API, dan PBB sebagai master template aplikasi yang mana master template tersebut nantinya akan digunakan sebagai symlink ke masing-masing desa pelanggan. 

Review Hasil Demo Saas
<img width="100%" alt="review" src="https://user-images.githubusercontent.com/68048807/178956334-ffede75f-78ee-44b2-98e4-ed0c4d890982.PNG">

Proses Instalasi Manualdi VPS Dashboard Saas
<img width="100%" alt="instlasi manual" src="https://user-images.githubusercontent.com/68048807/178956545-c589ad3b-6d03-4e91-9654-59fc12cd55d2.PNG">
 
Yang perlu di cheklist dalam issue ini:
- [x] Instalasi OpenSID Premium yang diambil dari repo https://github.com/OpenSID/rilis-premium
- [x] Instalasi OpenSID API yang diambil dari repo https://github.com/OpenSID/rilis-opensid-api
- [x] Instalasi Aplikasi PBB yang diambil dari repo https://github.com/OpenSID/rilis-pbb
- [x] Symlink OpenSID Premium di Dashboard Saas
- [x] Symlink OpenSID API di Dashboard Saas
- [x] Symlink Aplikasi PBB di Dashboard Saas

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/45
