### ISSUE TITLE
Versi Dashboard Saas

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#44]
Penamaan versi dahsboard saas seperti aplikasi lainnya sebagai pencatatan perkembangan aplikasi. 
saat ini sudah tersedia namun untuk pengubahannya masih di view, seharusnya dibuat helper di controller.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/38
