### ISSUE TITLE
Link ke website pelanggan yang ada pada daftar pelanggan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#45]
Saat ini link yang ada pada daftar langganan yang di dashboard ketika di klik merupakan link alamat devsaas.opendesa.id/alamatdomain sehingga akanmenemukan error 404 not found. 

<img width="100%" alt="link langganan" src="https://user-images.githubusercontent.com/68048807/178952170-af798cf6-da68-4601-b897-b70a65bb2622.PNG">

<img width="100%" alt="link langganan1" src="https://user-images.githubusercontent.com/68048807/178952213-3f90e4f8-7faa-4c7c-b80d-82f80978b7f0.PNG">

- [x] Harapannya diperbaiki Link yang di sesuai dengan alamat domain masing-masing desa, baik di halaman dashboard maupun di halaman pelanggan.
- [x] Perbaiki Link Basic Application.
- [x] Perbaiki Link Info.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/40
