### ISSUE TITLE
Semua Tema Pro harus sudah terpasang di Master Tema

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#47]
Issue ini lanjutan dari [Instalasi OpenSID, API, dan PBB menggunakan script](https://github.com/OpenSID/wiki-saas/issues/43)

Tema Pro yang disediakan oleh OpenSID saat ini ada 3 tema yang berada di repo private yaitu:

- [x] Denatra https://github.com/ariandii/denatra
- [x] Silir  https://github.com/OpenSID/tema-silir
- [x] Batuah https://github.com/rohmanudin05/batuah

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/52
