### ISSUE TITLE
Memasang Tema Pro pada Master Opensid

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#49]
Tema Pro yang disediakan oleh OpenSID saat ini ada 3 tema yang berada di repo private (lihat issue [Semua Tema Pro harus sudah terpasang di Master Tema ](https://github.com/OpenSID/wiki-saas/issues/47))

Pada issue ini memasang tema pro pada opensid desa yang sudah membeli tema pro.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/53
