### ISSUE TITLE
Symlink PhpMyadmin

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#52]
Pada layanan Dashboard Saas, untuk keamanan pada semua database yang ada di vps tersebut maka untuk mengakses ke PhpMyadmin tidak menggunakan https://www.nama-domain-saas/phpmyadmin melainkan menggunakan remote.

Adapun yang dapat digunakan adalah DBeaver yang dapat di download di https://dbeaver.io/download/  

Dengan adanya remote menggunakan DBeaver maka diperlukan symlink PhpMyadmin agar dapat diakses.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/41
