### ISSUE TITLE
Membuat database Dashboard Saas

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#53]
dengan adanya [issue #43 Instalasi OpenSID, API, dan PBB menggunakan script](https://github.com/OpenSID/wiki-saas/issues/43) bahwasanya diharapkan dapat mempermudah pelaksana pertama kali install dashboard saas, maka dari itu perlu juga database yang dibuat secara otomatis sehingga lebih mempermudah kembali proses instalasi awal.

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/dashboard-saas/pull/43
