### ISSUE TITLE
Default Server Layanan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#57]
Saat ini jika akan melakukan demo atau uji coba menggunakan https://layanan.opendesa.id seharus menggunakan https://devlayanan.opendesa.id, kemudian untuk merubahnya harus merubah pada master template di opensid, api, dan pbb, dalam hal ini kurang efisien, sehingga diperlukan perubahan hanya sekali saja.

- [x] config.php OpenSID
- [x] .env Api
- [x] .env Pbb
- [x] Merubah script BuildSite
- [x] Merubah script InstallMaster

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/46
