### ISSUE TITLE
Penamaan dan menghapus script

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#58]
Ada beberapa penamaan script yang perlu diperbaiki, dan ada script yang tidak digunakan sebaiknya dihapus.

- [x] pbb_migrasi seharusnya pbb_storage agar tidak sama penamaannya (BuildSite)
- [x] hapus setVhostSsl (BuildSite)
- [x] storage:link dasboard saas (InstallSaas)
- [x] penamaan database saas (InstallSaas)
- [x] mempersingkat perintah saas:install
- [x] script menjalankan index.php
- [x] cacert.pem
- [x] Berkaitan dengan issue https://github.com/OpenSID/wiki-saas/issues/40

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/47
