### ISSUE TITLE
Dashboard Saas : API Tema Pro

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#59]
Sediakan API untuk dipanggil oleh Layanan untuk membuat / memesan tema pro, sehingga Layanan akan mengirim info yg diperlukan.

Yang dihasilkan adalah tema pro akan tersedia di folder desa opensid yang telah memesan tema tersebut.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/55
