### ISSUE TITLE
Dashboard: deteksi dan atur pelanggan SaaS yg sudah berakhir

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#6]
Secara otomatis deteksi pelanggan SaaS yg masa langganannya sudah berakhir.

Jika sudah berakhir, lakukan sebagai berikut:

1. masa berakhir kurang dari 30 hari: 
    a. jika site diakses, tampilkan pesan site sudah suspended dan akan dihapus pada tgl x
    b. kirim peringatan pada hari 1, 7, 14, 21 setelah masa langganan berakhir ke alamat email dan Telegram kontak site ybs. Peringatan ini akan dilakukan aplikasi Layanan
2. masa berakhir sudah lebih dari 30 hari: hapus site ybs

**Comment by pandigresik** [comment]
sepertinya lebih masuk akal jika proses penonaktifan dan penghapusan site dilakukan oleh layanan bukan dashboard-saas, jadi aplikasi layanan mengirimkan request ke dashboard-saas untuk menonaktifkan / menghapus site desa tertentu

**Comment by eddieridwan** [comment]
@pandigresik proses nonaktifkan dan penghapusan berdasarkan waktu, yaitu perlu diterapkan menggunakan cron atau sejenisnya. Bisa dilakukan di Layanan, jika Layanan ditambahkan penjadwalan pemeriksaan status langganan. Kalau ada kendala pengiriman instruksi dari Layanan karena apapun, maka Dashboard SaaS tidak akan melakukan.

Sebaiknya Dashboard SaaS sendiri yg melakukan sehingga tidak harus bergantung pada keberhasilan instruksi dari Layanan.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/17

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/17
