### ISSUE TITLE
BUG: Terdapat Symlink premium jika install master terdapat perintah yang salah

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#60]
Ketika install master template, kemudian terdapat salah perintah misalkan php artisan master:install ---kode_desa=kodedesa --token_premium=token 
pada perintah tersebut seharusnya pada ---kode_desa adalah --kode_desa.

dengan kesalahan tersebut maka sudah terbentuk symlink premium, sehingga sudah tidak dapat clone dari repo rilis-premium.

berikut symink yang sudah terbentuk :
![error ada symlink premium](https://user-images.githubusercontent.com/68048807/180910289-8e6fee2f-2a4c-4882-814a-4cf9d699bc47.JPG)

catatan:
1. error tersebut hanya dapat dilihat ketika remote ssh menggunakan filezilla.
2. Panduan Install https://panduan.opendesa.id/id/dasbor-saas/instalasi

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/48
