### ISSUE TITLE
Konfigurasi APP_ENV, perbaiki hak akses

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#61]
- [x] Konfigurasi APP_ENV di .env bahwasanya aplikasi production atau local/development

- [x] Perbaiki Hak Akses
Ketika klik tombol Lihat Selengkapnya pada tabel pelanggan di dasbor, muncul error yang ditampilkan pada gambar berikut, yang disebabkan karena belum ada hak akses permission untuk storage dan bootstrap di aplikasi dasboard saas.
![error bootstrap](https://user-images.githubusercontent.com/68048807/181134345-2cf25230-9391-4358-a5a6-40bed0e2ad67.JPG)

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/dashboard-saas/pull/49
