### ISSUE TITLE
Install OpenSID, API dan PBB 5 bulan sebelumnya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#62]
- [x] 5 versi OpenSID sebelumnya
- [x] 5 versi OpenSID API sebelumnya
- [x] 5 versi Aplikasi PBB sebelumnya
- [x] Gunakan/panggil perintah di Install Master

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/wiki-saas/issues/62
