### ISSUE TITLE
Konfigurasi Git Token Github

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#63]
Issue ini berkaitan dengan issue #47
Untuk Install Tema harus yaitu dengan git clone dan harus ada memasukkan token github setiap install tema, jika ada 3 tema maka perlu ketikan sebanyak 3 kali, sehingga jika nantinya akan banyak tema maka akan merepotkan.

![git token](https://user-images.githubusercontent.com/68048807/182963418-2f477f2a-89b5-4e98-acdc-ade8b858d5af.JPG)

konfigurasikan token github di .env (buat di panduan)

**Comment by scqolbu24** [comment]
sudah ditambahkan pada panduan untuk konfigurasi token github.
https://panduan.opendesa.id/id/dasbor-saas/instalasi

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/54
