### ISSUE TITLE
Penyesuaian token pada pemasangan tema pro

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#65]
Penyesuaian token disini yang dimaksud adalah token premium, ketika pemasangan tema dengan menggunakan pemesanan melalui layanan maka akan ada perubahan token premium sehingga perlu adanya perubahan konfigurasi pada env di masing-masing aplikassi, yaitu opensid, api, dan pbb.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/58
