### ISSUE TITLE
List tema pro pada pelanggan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#67]
Berdasarkan [issue #47 Semua Tema Pro harus sudah terpasang di Master Tema](https://github.com/OpenSID/wiki-saas/issues/47), maka dibutuhkan list untuk tema pro yang terpasang di pelanggan. Ceklist sebagai berikut:
- [x] Hapus pada dasbor untuk link opensid umum.
- [x] Hapus pada sidebar menu opensid umum.
- [x] Tambah table tema
- [x] Tampilkan jumlah tema di dasbor
- [x] Tampilkan modal dialog pada klik jumlah tema di dasbor 
- [x] Tampilkan tema di pelanggan
- [x] Sesuaikan API install tema pro

**Comment by FirlianiF** [comment]
sudah digabung melalui pr https://github.com/OpenSID/dashboard-saas/pull/61
