### ISSUE TITLE
BUG : Validasi https://

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-siappakai#68]
Pada saat newsite dibuatkan validasi untuk menghapus "https://" dan "/"

contoh error

![Image](https://user-images.githubusercontent.com/68048807/183827321-fe8b1c69-c381-43c5-844a-c16cad907b49.JPG)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/107
