### ISSUE TITLE
Tampilkan keterangan panduan pada Tombol Tanda Tanya di Navbar

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#69]
- [x] Penjelasan singkat tentang dasbor saas
- [x] Keterangan ke panduan.opendesa.id 
- [x] Hapus menu yang tidak digunakan pada menu dropdown

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/62
