### ISSUE TITLE
Tambah Baru Tema Pro pada Saas

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#75]
saat ini tema pro yang sudah diterapkan ada 3 tema seperti yang dijelasakan pada issue https://github.com/OpenSID/wiki-saas/issues/47, kemudian pada saat review pengujian saas pada 26 Agustus 2022 diinformasikan ada penambahan tema pro sehingga dibutuhkan pemasangan baru tema tersebut. 

Penambahan tema pro yang akan ditambahkan sekarang adalah **Tema Denava** yang berada pada repo private https://github.com/ariandii/denava

Ada 2 yang perlu dilakukan untuk pemasangan tema baru tersebut:

 - [x] Penambahan tema pro setelah dasbor saas diinstall
 - [x] Penambahan tema pro bareng dengan install dasbor saas

**Comment by scqolbu24** [comment]
Pertimbangan Penambahan tema pro setelah dasbor saas diinstall tidak melalui database adalah jika menggunakan database harus update di masing-masing database VPS Layanan OpenSID Siap Pakai, 

Jika menggunakan PR maka hanya update 1 repo https://github.com/OpenSID/dashboard-saas kemudian Layanan OpenSID akan update secara otomatis.

Panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/memperbarui#menambahkan-tema-pro

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/72
