### ISSUE TITLE
Kembali ke versi sebelumnya pada desa tertentu

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#76]
Pada saat terjadinya rilis, ada beberapa desa yang mengalami bug dikarenakan salah satunya bisa disebabkan karena database atau yang lainnya. Sehingga perlu diubah ke versi sebelumnya agar dapat berjalan dengan normal.

Saat ini Saas menyediakan 6 versi dengan masing-masing versi diambil dari rilis setiap bulannya, berdasarkan usulan/pertanyaan dari pelaksana ketika uji coba 26 Agustus 2022, yaiut Saas dapat melakukan mundur versi ke rilis rev.

Struktur Folder pada Opensid untuk rilis setiap bulannya:
1. premium
2. premium_1
3. premium_2
4. premium_3
5. premium_4
6. premium_5

Tambahan untuk rilis setiap minggunya
1. premium_rev1
2. premium_rev2
3. premium_rev3
4. premium_rev4
5. premium_rev5

**Comment by scqolbu24** [comment]
Struktur Folder
Struktur Folder pada Opensid untuk rilis setiap bulannya:

premium
premium_1
premium_2
premium_3
premium_4
premium_5

Tambahan untuk rilis setiap minggunya
premium_rilis
premium_rev01
premium_rev02
premium_rev03
premium_rev04
premium_rev05

Keterangan:
1. premium adalah berisi tags yang terbaru, baik rilis setiap bulannya atau tiap mingguanya (rev)
2. premium_rilis adalah berisi tags rilis berjalan
3. premium_1 adalah rilis bulan sebelumnya (rilis - 1)
4. premium_2 adalah rilis bulan sebelumnya (rilis - 2)
5. premium_3 adalah rilis bulan sebelumnya (rilis - 3)
6. premium_4 adalah rilis bulan sebelumnya (rilis - 4)
7. premium_5 adalah rilis bulan sebelumnya (rilis - 5)
8. premium_rev01 adalah rilis revisi (mingggu pertama)
9. premium_rev02 adalah rilis revisi (mingggu kedua)
10. premium_rev03 adalah rilis revisi (mingggu ketiga)
11. premium_rev04 adalah rilis revisi (mingggu keempat)
12. premium_rev05 adalah rilis revisi (mingggu kelima)

**Comment by FirlianiF** [comment]
Pr untuk jalankan di sistem https://github.com/OpenSID/dashboard-saas/pull/76

**Comment by scqolbu24** [comment]
Untuk kembali ke versi sebelumnya:
- [ ] Backup database Otomatis mingguan https://github.com/OpenSID/wiki-saas/issues/87
- [ ] Download database backup terbaru (sediakan tombol download/unduh) https://github.com/OpenSID/wiki-saas/issues/92
- [ ] Backup database Otomatis bulanan
- [ ] Download database backup bulanan
- [ ] Tampilkan versi pada tabel pelanggan
- [ ] Tekan Tombol Kembali ke versi sebelumnya

**Comment by eddieridwan** [comment]
@scqolbu24 sepertinya alur ini kurang tepat. Untuk kembali ke versi sebelumnya, hanya bisa jika sudah ada backup sebelum update ke versi terbaru. Jadi bukan melakukan backup pada waktu mundur, karena alasan mundur biasanya karena database sudah rancu. Yaitu pada waktu minta mundur, databasenya belum tentu dalam kondisi baik. 

Backup otomatis harus dilakukan sebelum setiap update, baik itu update rilis baru tgl 1 atau rilis rev. Yaitu picu melakukan backup otomatis bukan semata-mata waktu, melainkan akan melakukan update.

**Comment by vickyrolanda** [comment]
> @scqolbu24 sepertinya alur ini kurang tepat. Untuk kembali ke versi sebelumnya, hanya bisa jika sudah ada backup sebelum update ke versi terbaru. Jadi bukan melakukan backup pada waktu mundur, karena alasan mundur biasanya karena database sudah rancu. Yaitu pada waktu minta mundur, databasenya belum tentu dalam kondisi baik.
> 
> Backup otomatis harus dilakukan sebelum setiap update, baik itu update rilis baru tgl 1 atau rilis rev. Yaitu picu melakukan backup otomatis bukan semata-mata waktu, melainkan akan melakukan update.

1. Versi mundur ini akan di terapkan hanya 1 versi sebelumnya , misalkan Rilis Rev02 maka hanya bisa mundur di Rilis Rev01 begitu juga untuk Rilis Premium, misalkan bulan ini RIlis 22.09 maka hanya bisa di mundurkan ke versi Rilis 22.08 saja.
2. Lalu untuk update versi baru akan di lakukan secara automatis setiap hari selasa pagi (01.00) dan Rilis Premium dilakukan setiap tanggal 2 Pagi (01.00)
3. Terkait Database akan backup automatis sebelum rilis rev (mingguan ketika dijalankan auto update maka jalan terlebih dahulu backup database) dan sebelum rilis premium (bulanan ketika dijalankan auto update maka jalan terlebih dahulu backup database)
4. Untuk terkait database dapat di download untuk versi mingguan & bulanan
5. Lalu untuk tombol kembali ke versi sebelumnya akan dapat di klik untuk di jalankan beserta dengan database hasil backup , Mingguan / Bulanan

**Comment by scqolbu24** [comment]
> 

Pak @eddieridwan ini hasil analisis dengan mas @vickyrolanda, mohon koreksinya pak.

**Comment by eddieridwan** [comment]
Saran saya OpenSID Siap Pakai tidak perlu bertanggung jawab proses backup mingguan/bulanan. Cukup hanya membuat backup sebelum melakukan update ke setiap rilis terbaru (tgl 1 maupun rev). Dan proses mundur cukup mengambil dari backup yg tersimpan di server, karena hanya akan ada satu backup. Kita ingin OpenSID Siap Pakai dirancang sesederhana mungkin.

Sebenarnya juga tidak perlu disediakan fitur untuk download backup yg dihasilkan. Backup yg disediakan Dasbor OpenSID SP hanya dimaksudkan untuk menjaga terjadinya masalah pada waktu update. Bukan untuk memenuhi kebutuhan backup pengguna selain itu.

Untuk backup selain itu, biar menjadi tanggung jawab desa sendiri.

**Comment by eddieridwan** [comment]
Perlu diingat, desa tidak akan diberi akses pada Dasbor OSS. Fitur download backup untuk kegunaan desa ada di OpenSID, bukan di Dasbor OSS.

**Comment by vickyrolanda** [comment]
> Saran saya OpenSID Siap Pakai tidak perlu bertanggung jawab proses backup mingguan/bulanan. Cukup hanya membuat backup sebelum melakukan update ke setiap rilis terbaru (tgl 1 maupun rev). Dan proses mundur cukup mengambil dari backup yg tersimpan di server, karena hanya akan ada satu backup. Kita ingin OpenSID Siap Pakai dirancang sesederhana mungkin.
> 
> Sebenarnya juga tidak perlu disediakan fitur untuk download backup yg dihasilkan. Backup yg disediakan Dasbor OpenSID SP hanya dimaksudkan untuk menjaga terjadinya masalah pada waktu update. Bukan untuk memenuhi kebutuhan backup pengguna selain itu.
> 
> Untuk backup selain itu, biar menjadi tanggung jawab desa sendiri.

oh iya untuk backup itu hanya di lakukan pembaruan setiap minggu jadi yang tersimpan itu hanya 1 database seminggu sebelum rilis saja, begitu ada rilis selanjutnya maka database tersebut akan di perbarui dengan database terbaru begitu juga untuk rilis bulanan pak.

**Comment by eddieridwan** [comment]
Picu membuat backup adalah akan dilakukannya update. Itu saja.

**Comment by scqolbu24** [comment]
Adanya backup database https://github.com/OpenSID/wiki-saas/issues/87, seperti yang didiskusikan pada saat pertemuan rutin
adalah penyebab dari issue ini, yaitu kembali ke versi sebelumnya setelah update mengalami bug.
Sehingga dalam pemahaman kami sebagai berikut:
Analisis / Opsi 1:
1. Backup database dilakukan setiap hari melalui cronjob yaitu jam 01.00 
   dan update akan dilakukan jam 03.00 ketika terjadi perubahan versi pada repo rilis 
2. Resikonya 
   a. server setiap hari melakukan backup database, baik dilakukan update versi ataupun tidak update.
   b. jika bug ketahuan setelah selisih 2 hari maka database sudah terupdate ke versi yang terbaru, 
      sehingga tidak memungkinkan mundur versi.

Analisis / Opsi 2:
1. Backup database dilakukan pada waktu tertentu:
   a. backup rutin 1 bulanan sebelum rilis bulanan, yaitu dilakukan pada tanggal 2 setiap jam 01.00
   b. backup rutin 1 minggu sebelum rilis mingguan (revisi), yaitu dilakukan setiap hari selasa jam 01.00
2. Resikonya 
   a. kapasitas server akan lebih banyak karena ada backup bulanan dan mingguan.
   b. jika bug ketahuan setelah selisih 2 hari maka bisa dilakukan mundur versi namun data waktu 2 hari tersebut akan hilang karena belum dilakukan backup
3. Kenapa perlu ada du backup mingguan dan bulanan, dikarenakan apabila rilis tanggal 01 dilakukan pada hari Rabu
   maka pada tanggal 02 hari Kamis jam 01.00 opensid akan melakukan update otomatis dengan versi terbaru, 
   kemudian jika terjadi bug dan akan mundur versi database yang perlu diambil adalah backup tanggal 02
   karena backup mingguan yang dilakukan setiap hari selasa belum ada. 

Demikian pak dari hasil Analisis kami, mohon koreksi dan masukannya sebaiknya bagaimana?

**Comment by eddieridwan** [comment]
@scqolbu24 @vickyrolanda , seperti berikut:  

1. Rilis tidak harus langsung diupdate. Terdeteksinya adanya rilis baru memicu dilakukannya backup + update pada tengah malam setelah rilis. Yaitu jadwalkan cronjob melakukan backup yg langsung diikuti oleh update.
2. Yaitu update ke rilis terbaru dapat digunakan oleh desa sehari setelah terdeteksinya ada rilis baru. Jadi misalnya rilis tgl 1 terupdate pada tgl 2; rev tgl 7 terupdate pada tgl 8, dstnya
3. Jadi backup dilakukan seiring dengan update dan tidak dijadwalkan terpisah.
4. Backup dan update selalu dijalankan pada waktu sepi di tengah malam sehingga tidak mengganggu layanan masyarakat. Dan tidak tergantung jam berapa programmer menerbitkan rilis, misalnya tidak peduli rilis pukul 09:00 pagi atau 12:00.
5. Penjadwalan backup + update di masing2 server dilakukan berjeda supaya tidak semua sekaligus; misalnya satu server 50 desa: jadwalkan 5 desa setiap 30 menit mulai pukul 22:00.
6. Jika desa minta melakukan mundur pada hari update + 2, mundur ke versi sebelumnya menggunakan backup sebelum update. Tidak mundur ke status database pada hari sebelumnya, karena database pada hari itu sudah migrasi dan sangat mungkin juga sudah rancu. Desa bisa dianjurkan membuat backup database secara manual sebelum meminta mundur versi, sekiranya ada perubahan sejak update yg ingin mereka selamatkan.


Diingatkan kembali. Dasbor OpenSID SP tidak melakukan backup selain untuk keperluan mundur versi. Jadi TIDAK melakukan backup mingguan atau bulanan. Hanya melakukan backup sebelum update.

Jadi hanya akan ada satu file backup di server untuk setiap desa. Yaitu backup sebelum setiap update akan menimpa backup sebelumnya.

**Comment by scqolbu24** [comment]
Baik pak @eddieridwan sudah paham dengan apa yang dimaksud. Terimakasih

**Comment by scqolbu24** [comment]
Tahapannya MUndur versi:
- [x] Backup database otomatis setelah mendeteksi adanya versi terbaru https://github.com/OpenSID/wiki-saas/issues/87
- [x] Update versi server secara otomatis setelah mendeteksi adanya versi terbaru https://github.com/OpenSID/wiki-saas/issues/88
- [x] Sediakan tombol download database jika diperlukan https://github.com/OpenSID/wiki-saas/issues/92
- [x] Tampilkan versi pada tabel pelanggan https://github.com/OpenSID/wiki-saas/issues/93
- [x] Sediakan tombol kembali ke versi sebelumnya https://github.com/OpenSID/wiki-saas/issues/94
