### ISSUE TITLE
Dibuatkan progress untuk mengetahui instalasi yang sudah selesai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#77]
Saat ini informasi pada _Monitoring Queue_ adalah _Running_, _Failded_, dan _Success_ 
namun tidak dijelaskan informasi progress dari aplikasi apa saja yang sudah selesai.

Harapannya ada informasi tentang proses yang sudah selesai

**Comment by scqolbu24** [comment]
Referensi : 
https://www.youtube.com/watch?v=HErI5i-a0NI

https://laravel.com/docs/8.x/horizon
https://www.youtube.com/watch?v=DjbQm4IZCYQ
https://www.youtube.com/watch?v=7LkYpwVPSiE

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/210
