### ISSUE TITLE
Terapkan OpenSID SaaS manual sebagai baseline, mengikuti cara Ahmad Afandi, Ariandi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#8]
Terapkan OpenSID SaaS secara manual di VPS SaaS Development, sebagai baseline, untuk memastikan kelayakan konsep SaaS.

**Comment by scqolbu24** [comment]
Menerapkan manual baseline opensid saas :
http://103.172.204.47/
http://103.172.204.47/desasatu
http://103.172.204.47/desadua

**Comment by FirlianiF** [comment]
sudah diterapkan manual baseline, berikut link-link nya:
https://devsaas.opendesa.id/
https://devsaas.opendesa.id/desasatu/
https://devsaas.opendesa.id/desadua/
