### ISSUE TITLE
Perubahan Nama Layanan OpenSID Siap Pakai

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#81]
Berdasarkan hasil evaluasi pada tanggal 25 Agustus 2022, yang mana Dasbor Saas sering diartikan 'Lebih Murah', maka diubah menjadi Layanan OpenSID Siap Pakai.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/69
