### ISSUE TITLE
Konfigurasi Running Queue dengan supervisor

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#83]
Pada saat mengirimkan perintah dari Layanan yang menggunakan perintah queue pada command terkadang success dan failed sehingga perlu dijalankan dari supervisor di server.

![monitoring queue](https://user-images.githubusercontent.com/68048807/187346255-754cb1d8-e7ef-4dd2-a95d-a33b62516035.JPG)

**Comment by scqolbu24** [comment]
Solusi dari @agungsugiarto https://www.youtube.com/watch?v=T9hfgkKgKOU

**Comment by scqolbu24** [comment]
Dokumentasi Laravel https://laravel.com/docs/8.x/queues#supervisor-configuration

**Comment by scqolbu24** [comment]
Sudah dibuatkan panduan pada https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/instalasi#konfigurasi-supervisor

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/dashboard-saas/pull/71
