### ISSUE TITLE
Meneliti Backup Database Otomatis

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#87]
Issue ini merupakan pengembangan dari issue https://github.com/OpenSID/wiki-saas/issues/76

Tujuan agar dapat mundur ke versi sebelumnya.

Beberapa yang perlu diperhatikan :
1. Performa cara yang paling efisien untuk backup dan restore database secara otomatis.
2. Berapa lama proses cronjob dan ukuran database.

Refrensi : 
https://github.com/spatie/laravel-backup

**Comment by scqolbu24** [comment]
referensi : 
https://www.youtube.com/watch?v=fQgZ8P35YHM

Spatie:
https://www.youtube.com/watch?v=2VoekC_RtbE
https://spatie.be/docs/laravel-backup/v8/introduction
https://github.com/spatie/db-dumper

**Comment by scqolbu24** [comment]
solusi ketika gagal backup https://stackoverflow.com/questions/38085933/general-error-mysqldump-is-not-recognized-as-an-internal-or-external-command

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/77

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/82
