### ISSUE TITLE
Perbaiki Symlink setelah Update Versi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#88]
Setelah Update versi symlink corupted atau tidak dapat diakses sehingga harus perlu disesuaikan dengan symlink yang terbaru.

- [x] OpenSID Premium
- [x] OpenSID API
- [x] Aplikasi PBB

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/dashboard-saas/pull/75

**Comment by scqolbu24** [comment]
Dengan adanya issue https://github.com/OpenSID/wiki-saas/issues/93, maka yang perlu diselesaiakan dalam issue ini adalah ubah versi pada tabel pelanggan.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/84
