### ISSUE TITLE
Buat dokumentasi ERD untuk Dashboard-SaaS

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#9]
Buat ERD Dashboard SaaS sesuai kebutuhan keseluruhan fitur.

Letakkan di [panduan.opendesa.id](https://panduan.opendesa.id), disertai penjelasan secukupnya.

**Comment by scqolbu24** [comment]
https://dbdiagram.io/d/62f5012cc2d9cf52fa8cf274
![dasbor_saas](https://user-images.githubusercontent.com/68048807/184142168-1484742f-ef05-47da-bacc-be5d7d45b44f.png)

**Comment by scqolbu24** [comment]
https://panduan.opendesa.id/id/dasbor-saas/dokumentasi#erd

**Comment by devrakapriyo** [comment]
sudah ok mas
