### ISSUE TITLE
Migrasi Otomatis

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#90]
Setelah Update ke rilis terbaru, dilakukan migrasi secara otomatis sesuai dengan versi tersebut.
Saat ini masih belum, seperti terlihat pada error berikut:
![migrasi otomatis](https://user-images.githubusercontent.com/68048807/190034421-eeaa4da2-2e7e-4be7-bba3-c852eed370b9.JPG)

**Comment by apidong** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/dashboard-saas/pull/86
