### ISSUE TITLE
Membuat Alur Mundur dan Maju dari versi sebelumnya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#91]

**Comment by vickyrolanda** [comment]
1. Versi mundur ini akan di terapkan hanya 1 versi sebelumnya , misalkan Rilis Rev02 maka hanya bisa mundur di Rilis Rev01  begitu juga untuk Rilis Premium, misalkan bulan ini RIlis 22.09 maka hanya bisa di mundurkan ke versi Rilis 22.08 saja.
2. Lalu untuk update versi baru akan di lakukan secara automatis setiap hari selasa pagi (01.00) dan Rilis Premium dilakukan setiap tanggal 2 Pagi (01.00)
3. Terkait Database akan backup automatis sebelum rilis rev (mingguan ketika dijalankan auto update maka jalan terlebih dahulu backup database) dan sebelum rilis premium (bulanan ketika dijalankan auto update maka jalan terlebih dahulu backup database) 
4. Untuk terkait database dapat di download untuk versi mingguan & bulanan
5. Lalu untuk tombol kembali ke versi sebelumnya akan dapat di klik untuk di jalankan beserta dengan database hasil backup , Mingguan / Bulanan

**Comment by eddieridwan** [comment]
Saran saya OpenSID Siap Pakai tidak perlu bertanggung jawab proses backup mingguan/bulanan. Cukup hanya membuat backup sebelum melakukan update ke setiap rilis terbaru (tgl 1 maupun rev). Dan proses mundur cukup mengambil dari backup yg tersimpan di server, karena hanya akan ada satu backup. Kita ingin OpenSID Siap Pakai dirancang sesederhana mungkin.

Sebenarnya juga tidak perlu disediakan fitur untuk download backup yg dihasilkan. Backup yg disediakan Dasbor OpenSID SP hanya dimaksudkan untuk menjaga terjadinya masalah pada waktu update. Bukan untuk memenuhi kebutuhan backup pengguna selain itu.

Untuk backup selain itu, biar menjadi tanggung jawab desa sendiri.

**Comment by scqolbu24** [comment]
Gambar Panduan:
![dasbor-saas3](https://user-images.githubusercontent.com/68048807/192177412-d08aabc7-f437-4f39-b1f9-24195503e4e2.jpg)
![pelanggan-fix-1](https://user-images.githubusercontent.com/68048807/192177419-d93ad1c2-cc8f-470a-ae3c-3cca7d186093.jpg)
![Dialog mundur versi](https://user-images.githubusercontent.com/68048807/192177430-92dc65ca-9659-4439-bd7e-4784f6650bb3.JPG)

**Comment by scqolbu24** [comment]
https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/dokumentasi#mundur-versi-sebelumnya
https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/halaman-administrasi#tabel-pelanggan

**Comment by vickyrolanda** [comment]
mas @devrakapriyo mohon dibantu di review ya mas soalnya ini terkait panduan mas.

**Comment by devrakapriyo** [comment]
> mas @devrakapriyo mohon dibantu di review ya mas soalnya ini terkait panduan mas.

baik mas
