### ISSUE TITLE
Tampilkan versi pada tabel pelanggan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#93]
1. Pada saat pelanggan pertama kali didaftarkan perlu diidentifikasi terlebih dahulu versi master yang diserver OpenSID Siap Pakai.
2. Setelah mengetahui versi di server maka diinput ke database pelanggan.
3. Kemudian tampilkan versi tersebut di tabel pelanggan.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/dashboard-saas/pull/83
