### ISSUE TITLE
Sediakan tombol kembali ke versi sebelumnya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#94]
Ketika tombol kembali ke versi sebelumnya, proses yang dilakukan diantaranya:
- [x] Hapus Database
- [x] Restore Database dari backup
- [x] Ubah symlink sesuai dengan versi mundurnya
- [x] Ubah versi pada tabel pelanggan

**Comment by eddieridwan** [comment]
@scqolbu24 @vickyrolanda juga perlu restore folder desa sebelum mundur versi.
Tambahkan backup folder desa juga sebelum update ke versi terbaru.

**Comment by scqolbu24** [comment]
Baik Pak @eddieridwan

**Comment by scqolbu24** [comment]
Ketika tombol kembali ke versi sebelumnya, proses yang dilakukan diantaranya:
- [x] Hapus Database
- [x] Buat Database
- [x] Restore Database dari backup
- [x] Ubah symlink sesuai dengan versi mundurnya
- [x] Ubah versi pada tabel pelanggan
- [x] Hapus folder desa yang lama
- [x] Restore Folder Desa

**Comment by scqolbu24** [comment]
referensi :
restore database : https://github.com/sdon2/sql-restore-laravel

**Comment by apidong** [comment]
sudah diperbaiki melalui pr https://github.com/OpenSID/dashboard-saas/pull/86
