### ISSUE TITLE
Config global directory master-opensid untuk akses versi premium

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-siappakai#96]
Ketika persiapan ujicoba dengan pelaksana dilakukan install ulang dari awal ditemukan ada yang perlu ditambahkan ketika install master-opensid yaitu perlu setting `sudo git config --global --add safe.directory [nama directory]`.

Perintah tersebut maka dapat menggunakan perintah `git describe --tags` agar dapat mengetahui versi opensid premium

Untuk mempermudah dimasukan kedalam script proses install master pada installMasterOpensid di file InstallMaster.php

![global](https://user-images.githubusercontent.com/68048807/191871272-bc8b0c60-2886-4f59-b580-90343ddacc26.JPG)

issue ini muncul setelah mengerjakan issue https://github.com/OpenSID/wiki-saas/issues/88 pada PR https://github.com/OpenSID/dashboard-saas/pull/84

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/dashboard-saas/pull/87
