### ISSUE TITLE
Uji proses pindah hosting ke OpenSID SiapPakai

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#97]
Yang sudah diuji adalah pembuatan instalasi OpenSID baru sama sekali.

Perlu juga diuji skenario desa yg sudah hosting di tempat lain pindah ke OpenSID SiapPakai. Yaitu, perlu:

- [ ] Transfer domain
- [ ] Restore folder desa
- [ ] Restore database
- [ ] Transfer kode aktivasi untuk beberapa tema pro

Uji untuk skenario berikut:

1. Hosting di luar OpenDesa
2. Menggunakan hosting di OpenDesa

**Comment by scqolbu24** [comment]
Proses dalam pindah hosting yang perlu dilakukan:
1. Arahkan DNS Domain ke server VPS OpenSID Siap Pakai
2. Buat Pelanggan OpenSID Siap Pakai sesuai dengan langkah-langkah di layanan:
    - [x] a. Pastikan alamat domain pada data Pelanggan di https://layanan.opendesa.id sudah sesuai dengan alamat domain yang akan digunakan.
    - [x] b. Buat Pemesanan
    - [x] c. Buat Pelanggan OpenSID Siap Pakai
4.  Sediakan Tombol Pada kolom Aksi di tabel pelanggan di OpenSID Siap Pakai untuk melakukan:
    a. OpenSID
    - [x] Hapus Database yang dibuat ketika generate Pelanggan Baru
    - [x] Buat Database Baru
    - [x] Unggah Database dari pindahan
    - [x] Restore Database dari Pindahan
    - [x] Hapus Folder Desa yang dibuat ketika generate Pelanggan Baru
    - [x] Unggah Folder Desa dari pindahan
    - [x] Restore Folder Desa
    - [x] Sesuaikan konfigurasi config.php dan database.php, termasuk aktivasi tema pro (dilakukan di layanan)
    
    b. Aplikasi PBB
    - [x] Hapus Database yang dibuat ketika generate Pelanggan Baru
    - [x] Buat Database Baru
    - [x] Unggah Database Baru 
    - [x] Restore Database

**Comment by scqolbu24** [comment]
Mas @vickyrolanda, mohon direview

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/dashboard-saas/pull/89
