### ISSUE TITLE
Panduan proses pindah hosting ke OpenSID SiapPakai

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-siappakai#98]
Sediakan panduan bagi pelaksana proses untuk memindahkan OpenSID yg sudah hosting di tempat lain pindah ke OpenSID SiapPakai. Yaitu, perlu menjelaskan proses:

- [x]  Transfer domain
- [x]  Restore folder desa
- [x]  Restore database
- [x]  Transfer kode aktivasi untuk beberapa tema pro

Jelaskan proses untuk skenario berikut:

1. Hosting di luar OpenDesa
2. Menggunakan hosting di OpenDesa

**Comment by scqolbu24** [comment]
- [x] Tingkatkan Max Upload pada php.ini
- [x] Install Unzip 
- [x] Phpinfo
- [x] DB phpmyadmin

**Comment by scqolbu24** [comment]
![tabel-pelangganv23 02](https://user-images.githubusercontent.com/68048807/221886506-1eb7812c-b755-48cf-ae66-bd89df59526d.jpg)

**Comment by scqolbu24** [comment]
![pindah hosting](https://user-images.githubusercontent.com/68048807/221890528-b02099b7-0205-4fda-9ae7-19b3ed052023.png)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui panduan https://panduan.opendesa.id/id/layanan-opensid-siap-pakai/halaman-administrasi#pindah-hosting
